/**
 * Chart geometry — pure functions, no React, no DOM.
 *
 * Two reasons this is its own package rather than a file inside the web
 * app, both from the Phase 3 spec:
 *
 *   - It is unit-testable without rendering anything. North Indian
 *     geometry is fiddly, and the failure mode is a chart that looks
 *     *almost* right, which no assertion about a rendered component
 *     catches. Here the polygons can be checked as polygons: do they
 *     tile the square, do any two overlap, is house 1 where it must be.
 *
 *   - Phase 10 reuses it verbatim under `react-native-svg`, so the
 *     mobile chart is provably identical to the web chart rather than a
 *     second implementation that drifts.
 *
 * Everything works in a unit square scaled to `SIZE`, so a caller picks
 * its own viewBox without the geometry knowing about CSS.
 */

export const SIZE = 100

/** 0 = Aries … 11 = Pisces, matching astro-service's SIGNS tuple. */
export type SignIndex = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11

/** 1..12. Never 0 — the Vedic convention counts the ascendant's own sign as house 1. */
export type HouseNumber = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12

export type ChartStyle = 'north' | 'south'

export interface Point {
  x: number
  y: number
}

/** One region of a chart: the polygon, and where a glyph goes inside it. */
export interface Cell {
  /** Corners in draw order. Closed implicitly — do not repeat the first. */
  polygon: Point[]
  /**
   * Where to anchor the cell's label (a house number or a sign name).
   * The polygon centroid is wrong for the corner triangles, which is
   * why this is computed per cell rather than derived by the caller.
   */
  label: Point
  /** Where planet glyphs stack, top-centre of the run. */
  glyphAnchor: Point
}

export interface HouseCell extends Cell {
  house: HouseNumber
}

export interface SignCell extends Cell {
  sign: SignIndex
  /** Grid position, south-Indian only. Row 0 is the top. */
  row: number
  column: number
}

export const SIGN_COUNT = 12

// ─── the rotation ────────────────────────────────────────────────────
//
// The single piece of astrology in this package, and the one everything
// else depends on. Inclusive counting: the ascendant's own sign is house
// 1, not house 0. Dropping the +1 shifts every planet by one house and
// still produces a chart that looks entirely plausible.

/** Which house a sign occupies, given the ascendant's sign. */
export function houseOfSign(sign: SignIndex, ascendant: SignIndex): HouseNumber {
  // Go's and JavaScript's % both keep the dividend's sign, so a sign
  // behind the ascendant needs the second fold.
  return ((((sign - ascendant) % SIGN_COUNT) + SIGN_COUNT) % SIGN_COUNT + 1) as HouseNumber
}

/** Which sign sits in a house, given the ascendant's sign. */
export function signOfHouse(house: HouseNumber, ascendant: SignIndex): SignIndex {
  return ((ascendant + house - 1) % SIGN_COUNT) as SignIndex
}

// ─── North Indian: houses fixed, signs rotate ────────────────────────
//
// A square with both diagonals drawn, plus the rhombus joining the four
// edge midpoints. That divides it into four rhombi (top, left, bottom,
// right) and eight corner triangles: twelve regions.
//
// House 1 is ALWAYS the top-centre rhombus, and the numbers run
// ANTICLOCKWISE from it. That is the convention a North Indian reader
// expects; running them clockwise produces a chart that is wrong in a
// way only someone who reads these will notice.
//
//        (0,0)      (50,0)      (100,0)
//           ┌──────────┬──────────┐
//           │ ╲   2    │   12   ╱ │
//           │   ╲      │      ╱   │
//    (0,50) │  3  ╲────┼────╱  11 │ (100,50)
//           │      ╲ 1 │  ╱       │
//           │   4   ╲  │ ╱   10   │
//           │      ╱  ╲│╱  ╲      │
//           │   5 ╱  7 │ 9   ╲    │
//           └──────────┴──────────┘
//        (0,100)   (50,100)   (100,100)

const H = SIZE / 2 // 50 — the edge midpoints
const Q = SIZE / 4 // 25 — the inner rhombus corners

/**
 * The twelve house regions, in house order.
 *
 * Hand-written rather than generated by rotation, because the four
 * rhombi and eight triangles are genuinely different shapes and a
 * "clever" generator would be harder to check than the coordinates
 * themselves. The tests verify the result tiles the square exactly,
 * which is the property a typo here breaks.
 */
export function northIndianHouses(): HouseCell[] {
  const cell = (
    house: HouseNumber,
    polygon: Point[],
    label: Point,
    glyphAnchor: Point,
  ): HouseCell => ({ house, polygon, label, glyphAnchor })

  return [
    // House 1 — top centre rhombus.
    cell(1, [p(H, 0), p(SIZE - Q, Q), p(H, H), p(Q, Q)], p(H, Q * 0.55), p(H, Q * 1.15)),
    // 2 and 3 — the top-left corner, split by the diagonal.
    cell(2, [p(0, 0), p(H, 0), p(Q, Q)], p(Q, Q * 0.42), p(Q, Q * 0.75)),
    cell(3, [p(0, 0), p(Q, Q), p(0, H)], p(Q * 0.42, Q), p(Q * 0.75, Q)),
    // House 4 — left centre rhombus.
    cell(4, [p(0, H), p(Q, Q), p(H, H), p(Q, SIZE - Q)], p(Q * 0.6, H), p(Q * 1.2, H)),
    // 5 and 6 — the bottom-left corner.
    cell(5, [p(0, H), p(Q, SIZE - Q), p(0, SIZE)], p(Q * 0.42, SIZE - Q), p(Q * 0.75, SIZE - Q)),
    cell(6, [p(0, SIZE), p(Q, SIZE - Q), p(H, SIZE)], p(Q, SIZE - Q * 0.42), p(Q, SIZE - Q * 0.75)),
    // House 7 — bottom centre rhombus.
    cell(7, [p(H, SIZE), p(Q, SIZE - Q), p(H, H), p(SIZE - Q, SIZE - Q)],
      p(H, SIZE - Q * 0.55), p(H, SIZE - Q * 1.15)),
    // 8 and 9 — the bottom-right corner.
    cell(8, [p(H, SIZE), p(SIZE - Q, SIZE - Q), p(SIZE, SIZE)],
      p(SIZE - Q, SIZE - Q * 0.42), p(SIZE - Q, SIZE - Q * 0.75)),
    cell(9, [p(SIZE, SIZE), p(SIZE - Q, SIZE - Q), p(SIZE, H)],
      p(SIZE - Q * 0.42, SIZE - Q), p(SIZE - Q * 0.75, SIZE - Q)),
    // House 10 — right centre rhombus.
    cell(10, [p(SIZE, H), p(SIZE - Q, SIZE - Q), p(H, H), p(SIZE - Q, Q)],
      p(SIZE - Q * 0.6, H), p(SIZE - Q * 1.2, H)),
    // 11 and 12 — the top-right corner.
    cell(11, [p(SIZE, H), p(SIZE - Q, Q), p(SIZE, 0)],
      p(SIZE - Q * 0.42, Q), p(SIZE - Q * 0.75, Q)),
    cell(12, [p(SIZE, 0), p(SIZE - Q, Q), p(H, 0)],
      p(SIZE - Q, Q * 0.42), p(SIZE - Q, Q * 0.75)),
  ]
}

// ─── South Indian: signs fixed, houses rotate ────────────────────────
//
// A 4x4 grid with the middle four cells hollow. The signs are ALWAYS in
// the same cells — Pisces top-left, then clockwise — which is what makes
// a South Indian chart readable at a glance to someone used to it: the
// eye goes to a fixed position for a given sign.
//
// The ascendant is marked with a diagonal in its cell rather than by
// moving anything.

/** Sign in each grid position, reading clockwise from the top-left. */
const SOUTH_LAYOUT: ReadonlyArray<readonly [row: number, column: number, sign: SignIndex]> = [
  [0, 0, 11], // Pisces
  [0, 1, 0], // Aries
  [0, 2, 1], // Taurus
  [0, 3, 2], // Gemini
  [1, 3, 3], // Cancer
  [2, 3, 4], // Leo
  [3, 3, 5], // Virgo
  [3, 2, 6], // Libra
  [3, 1, 7], // Scorpio
  [3, 0, 8], // Sagittarius
  [2, 0, 9], // Capricorn
  [1, 0, 10], // Aquarius
]

/**
 * The twelve sign cells, clockwise from Pisces at the top-left.
 *
 * Returned in layout order rather than sign order, because that is the
 * order a reader's eye travels and the order the SVG should emit — a
 * screen reader following the DOM then hears the chart the way it is
 * drawn.
 */
export function southIndianSigns(): SignCell[] {
  const side = SIZE / 4

  return SOUTH_LAYOUT.map(([row, column, sign]) => {
    const x = column * side
    const y = row * side
    return {
      sign,
      row,
      column,
      polygon: [p(x, y), p(x + side, y), p(x + side, y + side), p(x, y + side)],
      // Sign name top-left inside the cell, glyphs below it. Centring
      // the name would put it where the planets go, and a cell with four
      // planets in it is the common case, not the exception.
      label: p(x + side * 0.12, y + side * 0.22),
      glyphAnchor: p(x + side * 0.12, y + side * 0.5),
    }
  })
}

/**
 * The hollow middle, as one rectangle.
 *
 * Returned rather than assumed so a caller can put the chart's title or
 * the ascendant summary there without recomputing the grid.
 */
export function southIndianCentre(): Point[] {
  const side = SIZE / 4
  return [
    p(side, side),
    p(side * 3, side),
    p(side * 3, side * 3),
    p(side, side * 3),
  ]
}

// ─── shared helpers ──────────────────────────────────────────────────

/**
 * An SVG `points` attribute for a polygon.
 *
 * Rounded to three decimals: the coordinates are exact sixteenths of the
 * box, and full float precision makes an SVG diff unreadable without
 * changing a single rendered pixel.
 */
export function toPoints(polygon: Point[]): string {
  return polygon.map((point) => `${round(point.x)},${round(point.y)}`).join(' ')
}

/**
 * Where to place the nth planet glyph in a cell.
 *
 * Stacked downward from the anchor, and wrapped into two columns past
 * four. A stellium of six planets in one sign is common — Phase 2's
 * fixture set has them — and a single column would overflow the cell.
 */
export function glyphPosition(
  cell: Cell,
  index: number,
  style: ChartStyle,
  total: number,
): Point {
  const perColumn = 4
  const lineHeight = style === 'south' ? SIZE * 0.045 : SIZE * 0.04
  const columnWidth = SIZE * 0.075

  const column = Math.floor(index / perColumn)
  const row = index % perColumn

  const columns = Math.max(1, Math.ceil(total / perColumn))
  const rowsHere = Math.max(1, Math.min(total - column * perColumn, perColumn))

  /*
    Centred on the anchor, not grown down and to the right from it.

    The North Indian houses are triangles and the narrow ones — 3, 5, 9,
    11 — taper to a point. Stacking downward from the centroid runs out
    of the polygon: in house 11, whose apex is at x=75, the valid band at
    the glyph column x=81.25 is y in [18.75, 31.25], and the third glyph
    landed at y=33. It was DRAWN IN THE NEIGHBOURING HOUSE.

    That is a correctness bug a reader can see — a planet shown in the
    wrong house — and it was invisible to every test: the visually-hidden
    table renders `planet.house` from the data and so is right either
    way, and the stacking test used two planets, which fits.

    Centring makes the stack symmetric about the anchor, so n glyphs span
    half the height in each direction. Found by rendering all 30 golden
    fixtures and testing each glyph against its own polygon.
  */
  const wanted = {
    x: cell.glyphAnchor.x + (column - (columns - 1) / 2) * columnWidth,
    y: cell.glyphAnchor.y + (row - (rowsHere - 1) / 2) * lineHeight,
  }

  /*
    Then pulled back inside, if centring was not enough.

    Centring fixes the common case. It does not fix a stellium: the
    narrow triangles taper, and six glyphs at this line height simply do
    not fit in house 11 however they are arranged. Without a clamp the
    overflow lands in the NEIGHBOURING house, which draws a planet
    somewhere it is not.

    The trade is deliberate. A crowded house renders its glyphs bunched
    against the edge, which is ugly and readable and obviously crowded.
    The alternative is tidy and wrong. Real printed charts solve this by
    shrinking the text in a crowded house; that is a renderer concern —
    this package owns only where a glyph may be.
  */
  const point = pullInside(cell.polygon, cell.glyphAnchor, wanted)
  return { x: round(point.x), y: round(point.y) }
}

/**
 * The furthest point toward `wanted` that is still inside the polygon.
 *
 * Binary search along the segment from a known-interior point. Twenty
 * iterations puts it within a millionth of the boundary, and the
 * `INSET` keeps it a hair inside so a glyph never sits exactly on an
 * edge shared with the next region.
 */
function pullInside(polygon: Point[], interior: Point, wanted: Point): Point {
  if (pointInPolygon(polygon, wanted)) return wanted

  const INSET = 0.98
  let lo = 0
  let hi = 1

  for (let i = 0; i < 20; i++) {
    const mid = (lo + hi) / 2
    const at = {
      x: interior.x + (wanted.x - interior.x) * mid,
      y: interior.y + (wanted.y - interior.y) * mid,
    }
    if (pointInPolygon(polygon, at)) lo = mid
    else hi = mid
  }

  const t = lo * INSET
  return {
    x: interior.x + (wanted.x - interior.x) * t,
    y: interior.y + (wanted.y - interior.y) * t,
  }
}

/**
 * Ray casting. Exported because both the geometry tests and the
 * renderer's fixture test ask the same question, and two copies of a
 * point-in-polygon test is two chances to get the winding wrong.
 */
export function pointInPolygon(polygon: Point[], point: Point): boolean {
  let inside = false
  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
    const a = polygon[i]!
    const b = polygon[j]!
    if (a.y > point.y === b.y > point.y) continue
    if (point.x < ((b.x - a.x) * (point.y - a.y)) / (b.y - a.y) + a.x) inside = !inside
  }
  return inside
}

function p(x: number, y: number): Point {
  return { x, y }
}

function round(value: number): number {
  return Math.round(value * 1000) / 1000
}

/**
 * Twice the signed area of a polygon — the shoelace sum.
 *
 * Exported because the tests use it to prove the twelve regions tile the
 * square exactly, which is the property that catches a mistyped
 * coordinate. Signed, so the tests can also assert a consistent winding.
 */
export function signedArea2(polygon: Point[]): number {
  let total = 0
  for (let i = 0; i < polygon.length; i++) {
    const a = polygon[i]!
    const b = polygon[(i + 1) % polygon.length]!
    total += a.x * b.y - b.x * a.y
  }
  return total
}

export function area(polygon: Point[]): number {
  return Math.abs(signedArea2(polygon)) / 2
}
