// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ailogs.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAIUsageByJob = `-- name: GetAIUsageByJob :many
SELECT
    job_type,
    COUNT(*)                                      AS request_count,
    COALESCE(SUM(cost_micros), 0)::BIGINT         AS cost_micros,
    COALESCE(
        percentile_disc(0.5) WITHIN GROUP (ORDER BY latency_ms), 0
    )::INTEGER                                    AS p50_latency_ms,
    COALESCE(
        percentile_disc(0.95) WITHIN GROUP (ORDER BY latency_ms), 0
    )::INTEGER                                    AS p95_latency_ms,
    -- Cache hit rate: reads over reads-plus-fresh. NULLIF guards the
    -- division when a job made no calls in the window, which is a
    -- quiet hour rather than a divide-by-zero.
    COALESCE(SUM(cached_tokens), 0)::BIGINT       AS cached_tokens,
    COALESCE(SUM(input_tokens), 0)::BIGINT        AS input_tokens
FROM ai_request_logs
WHERE created_at >= $1 AND created_at < $2
GROUP BY job_type
ORDER BY cost_micros DESC
`

type GetAIUsageByJobParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

type GetAIUsageByJobRow struct {
	JobType      string
	RequestCount int64
	CostMicros   int64
	P50LatencyMs int32
	P95LatencyMs int32
	CachedTokens int64
	InputTokens  int64
}

// The same window, grouped. p50 and p95 latency come from
// percentile_disc rather than an average: an average latency hides the
// tail, and the tail is what users notice.
func (q *Queries) GetAIUsageByJob(ctx context.Context, arg GetAIUsageByJobParams) ([]GetAIUsageByJobRow, error) {
	rows, err := q.db.Query(ctx, getAIUsageByJob, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAIUsageByJobRow{}
	for rows.Next() {
		var i GetAIUsageByJobRow
		if err := rows.Scan(
			&i.JobType,
			&i.RequestCount,
			&i.CostMicros,
			&i.P50LatencyMs,
			&i.P95LatencyMs,
			&i.CachedTokens,
			&i.InputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAIUsageSummary = `-- name: GetAIUsageSummary :one
SELECT
    COUNT(*)                                         AS request_count,
    COALESCE(SUM(input_tokens), 0)::BIGINT           AS input_tokens,
    COALESCE(SUM(output_tokens), 0)::BIGINT          AS output_tokens,
    COALESCE(SUM(cached_tokens), 0)::BIGINT          AS cached_tokens,
    COALESCE(SUM(cache_write_tokens), 0)::BIGINT     AS cache_write_tokens,
    COALESCE(SUM(cost_micros), 0)::BIGINT            AS cost_micros,
    COALESCE(SUM(model_calls), 0)::BIGINT            AS model_calls,
    COUNT(*) FILTER (WHERE regenerated)              AS regenerated_count,
    COUNT(*) FILTER (WHERE NOT validation_passed)    AS failed_count
FROM ai_request_logs
WHERE created_at >= $1 AND created_at < $2
`

type GetAIUsageSummaryParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

type GetAIUsageSummaryRow struct {
	RequestCount     int64
	InputTokens      int64
	OutputTokens     int64
	CachedTokens     int64
	CacheWriteTokens int64
	CostMicros       int64
	ModelCalls       int64
	RegeneratedCount int64
	FailedCount      int64
}

// Totals over a window, for the admin usage view.
//
// COALESCE on every aggregate: SUM over zero rows is NULL, and a
// dashboard rendering "null requests, null cost" for a quiet hour is
// indistinguishable from a broken query.
//
// `cost_micros` is summed as BIGINT and returned as BIGINT. No cast to
// NUMERIC anywhere — invariant 4, and a NUMERIC that reaches Go through
// a float is exactly the bug the rule exists to prevent.
func (q *Queries) GetAIUsageSummary(ctx context.Context, arg GetAIUsageSummaryParams) (GetAIUsageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAIUsageSummary, arg.CreatedAt, arg.CreatedAt_2)
	var i GetAIUsageSummaryRow
	err := row.Scan(
		&i.RequestCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.CacheWriteTokens,
		&i.CostMicros,
		&i.ModelCalls,
		&i.RegeneratedCount,
		&i.FailedCount,
	)
	return i, err
}

const insertAIRequestLog = `-- name: InsertAIRequestLog :one

INSERT INTO ai_request_logs (
    trace_id, user_id, conversation_id,
    job_type, intent,
    provider_id, model, tier,
    prompt_version, context_version,
    input_tokens, output_tokens, cached_tokens, cache_write_tokens,
    latency_ms, cost_micros,
    finish_reason, safety_flags, validation_passed,
    regenerated, model_calls
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
RETURNING id, trace_id, user_id, conversation_id, job_type, intent, provider_id, model, tier, prompt_version, context_version, input_tokens, output_tokens, cached_tokens, cache_write_tokens, latency_ms, cost_micros, finish_reason, safety_flags, validation_passed, regenerated, model_calls, created_at
`

type InsertAIRequestLogParams struct {
	TraceID          string
	UserID           pgtype.UUID
	ConversationID   pgtype.UUID
	JobType          string
	Intent           *string
	ProviderID       string
	Model            string
	Tier             string
	PromptVersion    string
	ContextVersion   string
	InputTokens      int32
	OutputTokens     int32
	CachedTokens     int32
	CacheWriteTokens int32
	LatencyMs        int32
	CostMicros       int64
	FinishReason     string
	SafetyFlags      []byte
	ValidationPassed bool
	Regenerated      bool
	ModelCalls       int32
}

// Every model call, written by Go from the telemetry Python returned.
// See docs/specs/PHASE-04-AI-INFRASTRUCTURE.md §8.
//
// No query here selects message content, because no column holds any.
// Called inside the same transaction as the message write (Phase 5), so
// a request that cost money cannot be missing from the bill because a
// separate logging call failed.
func (q *Queries) InsertAIRequestLog(ctx context.Context, arg InsertAIRequestLogParams) (AiRequestLog, error) {
	row := q.db.QueryRow(ctx, insertAIRequestLog,
		arg.TraceID,
		arg.UserID,
		arg.ConversationID,
		arg.JobType,
		arg.Intent,
		arg.ProviderID,
		arg.Model,
		arg.Tier,
		arg.PromptVersion,
		arg.ContextVersion,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.CacheWriteTokens,
		arg.LatencyMs,
		arg.CostMicros,
		arg.FinishReason,
		arg.SafetyFlags,
		arg.ValidationPassed,
		arg.Regenerated,
		arg.ModelCalls,
	)
	var i AiRequestLog
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.UserID,
		&i.ConversationID,
		&i.JobType,
		&i.Intent,
		&i.ProviderID,
		&i.Model,
		&i.Tier,
		&i.PromptVersion,
		&i.ContextVersion,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.CacheWriteTokens,
		&i.LatencyMs,
		&i.CostMicros,
		&i.FinishReason,
		&i.SafetyFlags,
		&i.ValidationPassed,
		&i.Regenerated,
		&i.ModelCalls,
		&i.CreatedAt,
	)
	return i, err
}

const listAIRequestLogsForUser = `-- name: ListAIRequestLogsForUser :many
SELECT id, trace_id, user_id, conversation_id, job_type, intent, provider_id, model, tier, prompt_version, context_version, input_tokens, output_tokens, cached_tokens, cache_write_tokens, latency_ms, cost_micros, finish_reason, safety_flags, validation_passed, regenerated, model_calls, created_at FROM ai_request_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAIRequestLogsForUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

// Newest first, served by ai_logs_user_idx.
func (q *Queries) ListAIRequestLogsForUser(ctx context.Context, arg ListAIRequestLogsForUserParams) ([]AiRequestLog, error) {
	rows, err := q.db.Query(ctx, listAIRequestLogsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiRequestLog{}
	for rows.Next() {
		var i AiRequestLog
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.UserID,
			&i.ConversationID,
			&i.JobType,
			&i.Intent,
			&i.ProviderID,
			&i.Model,
			&i.Tier,
			&i.PromptVersion,
			&i.ContextVersion,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.CacheWriteTokens,
			&i.LatencyMs,
			&i.CostMicros,
			&i.FinishReason,
			&i.SafetyFlags,
			&i.ValidationPassed,
			&i.Regenerated,
			&i.ModelCalls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIRequestsForUser = `-- name: ListAIRequestsForUser :many
SELECT
    id,
    job_type,
    intent,
    model,
    tier,
    prompt_version,
    input_tokens,
    output_tokens,
    cached_tokens,
    latency_ms,
    cost_micros,
    finish_reason,
    safety_flags,
    validation_passed,
    created_at
FROM ai_request_logs
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAIRequestsForUserRow struct {
	ID               pgtype.UUID
	JobType          string
	Intent           *string
	Model            string
	Tier             string
	PromptVersion    string
	InputTokens      int32
	OutputTokens     int32
	CachedTokens     int32
	LatencyMs        int32
	CostMicros       int64
	FinishReason     string
	SafetyFlags      []byte
	ValidationPassed bool
	CreatedAt        time.Time
}

// Every AI request this person made, for their data export.
//
// PHASE-04 §8 keeps message CONTENT out of this table entirely, so what
// a person receives here is the shape of their usage and nothing they
// wrote: when, which job, which intent, what it cost. That is still
// personal data — "asked about medical matters on these dates" is a
// fact about a person — which is why it is exported rather than filed
// as telemetry.
//
// `cost_micros` is included deliberately. Phase 7 bills from this
// table, and an export that hides the number a charge is computed from
// would be the one field a person most reasonably wants to check.
func (q *Queries) ListAIRequestsForUser(ctx context.Context, userID pgtype.UUID) ([]ListAIRequestsForUserRow, error) {
	rows, err := q.db.Query(ctx, listAIRequestsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAIRequestsForUserRow{}
	for rows.Next() {
		var i ListAIRequestsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.Intent,
			&i.Model,
			&i.Tier,
			&i.PromptVersion,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.LatencyMs,
			&i.CostMicros,
			&i.FinishReason,
			&i.SafetyFlags,
			&i.ValidationPassed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAISafetyIncidents = `-- name: ListAISafetyIncidents :many
SELECT id, trace_id, user_id, conversation_id, job_type, intent, provider_id, model, tier, prompt_version, context_version, input_tokens, output_tokens, cached_tokens, cache_write_tokens, latency_ms, cost_micros, finish_reason, safety_flags, validation_passed, regenerated, model_calls, created_at FROM ai_request_logs
WHERE validation_passed = FALSE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAISafetyIncidentsParams struct {
	Limit  int32
	Offset int32
}

// The admin incident feed. Served by the PARTIAL index, so this stays
// fast as the table grows — failures are a small fraction of rows and a
// full index on the boolean would be scanned rather than used.
func (q *Queries) ListAISafetyIncidents(ctx context.Context, arg ListAISafetyIncidentsParams) ([]AiRequestLog, error) {
	rows, err := q.db.Query(ctx, listAISafetyIncidents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiRequestLog{}
	for rows.Next() {
		var i AiRequestLog
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.UserID,
			&i.ConversationID,
			&i.JobType,
			&i.Intent,
			&i.ProviderID,
			&i.Model,
			&i.Tier,
			&i.PromptVersion,
			&i.ContextVersion,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.CacheWriteTokens,
			&i.LatencyMs,
			&i.CostMicros,
			&i.FinishReason,
			&i.SafetyFlags,
			&i.ValidationPassed,
			&i.Regenerated,
			&i.ModelCalls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
