// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: astrology.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlaces = `-- name: CountPlaces :one
SELECT count(*) FROM places
`

func (q *Queries) CountPlaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBirthProfile = `-- name: CreateBirthProfile :one


INSERT INTO birth_profiles (
    user_id, label, birth_date, birth_time, time_accuracy,
    birth_place, latitude, longitude, timezone, utc_offset_min, utc_instant,
    source, version
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, label, birth_date, birth_time, time_accuracy, birth_place, latitude, longitude, timezone, utc_offset_min, utc_instant, source, verified, version, superseded_by, is_active, created_at
`

type CreateBirthProfileParams struct {
	UserID       pgtype.UUID
	Label        string
	BirthDate    pgtype.Date
	BirthTime    pgtype.Time
	TimeAccuracy string
	BirthPlace   string
	Latitude     float64
	Longitude    float64
	Timezone     string
	UtcOffsetMin int32
	UtcInstant   time.Time
	Source       string
	Version      int32
}

// Astrology queries. See docs/specs/PHASE-02-ASTROLOGY-ENGINE.md §3.
//
// Every read of a birth profile or a chart is scoped by user_id in the
// SQL itself, not by a check in the handler. A chart is among the most
// sensitive objects in the system, and a predicate in the query is a
// guarantee the caller cannot forget to apply.
// ─── birth profiles ──────────────────────────────────────────────────
func (q *Queries) CreateBirthProfile(ctx context.Context, arg CreateBirthProfileParams) (BirthProfile, error) {
	row := q.db.QueryRow(ctx, createBirthProfile,
		arg.UserID,
		arg.Label,
		arg.BirthDate,
		arg.BirthTime,
		arg.TimeAccuracy,
		arg.BirthPlace,
		arg.Latitude,
		arg.Longitude,
		arg.Timezone,
		arg.UtcOffsetMin,
		arg.UtcInstant,
		arg.Source,
		arg.Version,
	)
	var i BirthProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.BirthDate,
		&i.BirthTime,
		&i.TimeAccuracy,
		&i.BirthPlace,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.UtcOffsetMin,
		&i.UtcInstant,
		&i.Source,
		&i.Verified,
		&i.Version,
		&i.SupersededBy,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateBirthProfile = `-- name: DeactivateBirthProfile :execrows
UPDATE birth_profiles
SET is_active = FALSE
WHERE id = $1 AND user_id = $2 AND is_active = TRUE
`

type DeactivateBirthProfileParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeactivateBirthProfile(ctx context.Context, arg DeactivateBirthProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateBirthProfile, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDashasForChart = `-- name: DeleteDashasForChart :execrows
DELETE FROM dashas WHERE chart_id = $1
`

// Recomputing replaces the whole tree. Deleting first keeps it a tree
// rather than two overlapping generations of one.
func (q *Queries) DeleteDashasForChart(ctx context.Context, chartID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDashasForChart, chartID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTransitsBefore = `-- name: DeleteTransitsBefore :execrows
DELETE FROM transits WHERE timestamp < $1
`

func (q *Queries) DeleteTransitsBefore(ctx context.Context, timestamp time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransitsBefore, timestamp)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findDashaAt = `-- name: FindDashaAt :many
SELECT d.id, d.chart_id, d.system, d.planet, d.start_date, d.end_date, d.level, d.parent_id, d.metadata FROM dashas d
JOIN charts c ON c.id = d.chart_id
JOIN birth_profiles p ON p.id = c.birth_profile_id
WHERE d.chart_id = $1
  AND p.user_id = $2
  AND d.start_date <= $3
  AND d.end_date > $3
ORDER BY d.level
`

type FindDashaAtParams struct {
	ChartID pgtype.UUID
	UserID  pgtype.UUID
	At      time.Time
}

// Which periods were running at a given instant — one per level, so a
// caller gets the Maha, Antar and Pratyantar in a single round trip.
//
// Half-open interval: start <= t < end. A closed interval would return
// two rows on the boundary instant, since one period's end is the next
// one's start.
func (q *Queries) FindDashaAt(ctx context.Context, arg FindDashaAtParams) ([]Dasha, error) {
	rows, err := q.db.Query(ctx, findDashaAt, arg.ChartID, arg.UserID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dasha{}
	for rows.Next() {
		var i Dasha
		if err := rows.Scan(
			&i.ID,
			&i.ChartID,
			&i.System,
			&i.Planet,
			&i.StartDate,
			&i.EndDate,
			&i.Level,
			&i.ParentID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBirthProfile = `-- name: GetBirthProfile :one
SELECT id, user_id, label, birth_date, birth_time, time_accuracy, birth_place, latitude, longitude, timezone, utc_offset_min, utc_instant, source, verified, version, superseded_by, is_active, created_at FROM birth_profiles
WHERE id = $1 AND user_id = $2
`

type GetBirthProfileParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Scoped by user. A caller asking for someone else's profile gets no
// row, which the handler turns into a 404 — never a 403, because a 403
// confirms the row exists.
func (q *Queries) GetBirthProfile(ctx context.Context, arg GetBirthProfileParams) (BirthProfile, error) {
	row := q.db.QueryRow(ctx, getBirthProfile, arg.ID, arg.UserID)
	var i BirthProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.BirthDate,
		&i.BirthTime,
		&i.TimeAccuracy,
		&i.BirthPlace,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.UtcOffsetMin,
		&i.UtcInstant,
		&i.Source,
		&i.Verified,
		&i.Version,
		&i.SupersededBy,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getChart = `-- name: GetChart :one
SELECT c.id, c.birth_profile_id, c.chart_type, c.calculation_system, c.ayanamsa, c.house_system, c.engine_version, c.chart_data, c.computed_at FROM charts c
JOIN birth_profiles p ON p.id = c.birth_profile_id
WHERE c.birth_profile_id = $1
  AND c.chart_type = $2
  AND c.calculation_system = $3
  AND c.ayanamsa = $4
  AND c.house_system = $5
  AND p.user_id = $6
`

type GetChartParams struct {
	BirthProfileID    pgtype.UUID
	ChartType         string
	CalculationSystem string
	Ayanamsa          string
	HouseSystem       string
	UserID            pgtype.UUID
}

// Joined to birth_profiles so ownership is enforced in the same
// statement that fetches the data. A separate ownership check is a
// check someone can forget.
func (q *Queries) GetChart(ctx context.Context, arg GetChartParams) (Chart, error) {
	row := q.db.QueryRow(ctx, getChart,
		arg.BirthProfileID,
		arg.ChartType,
		arg.CalculationSystem,
		arg.Ayanamsa,
		arg.HouseSystem,
		arg.UserID,
	)
	var i Chart
	err := row.Scan(
		&i.ID,
		&i.BirthProfileID,
		&i.ChartType,
		&i.CalculationSystem,
		&i.Ayanamsa,
		&i.HouseSystem,
		&i.EngineVersion,
		&i.ChartData,
		&i.ComputedAt,
	)
	return i, err
}

const getPlace = `-- name: GetPlace :one
SELECT id, name, ascii_name, admin1, country_code, latitude, longitude, timezone, population FROM places WHERE id = $1
`

func (q *Queries) GetPlace(ctx context.Context, id int32) (Place, error) {
	row := q.db.QueryRow(ctx, getPlace, id)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AsciiName,
		&i.Admin1,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.Population,
	)
	return i, err
}

const insertDasha = `-- name: InsertDasha :one

INSERT INTO dashas (chart_id, system, planet, start_date, end_date, level, parent_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, chart_id, system, planet, start_date, end_date, level, parent_id, metadata
`

type InsertDashaParams struct {
	ChartID   pgtype.UUID
	System    string
	Planet    string
	StartDate time.Time
	EndDate   time.Time
	Level     int16
	ParentID  pgtype.UUID
	Metadata  []byte
}

// ─── dashas ──────────────────────────────────────────────────────────
func (q *Queries) InsertDasha(ctx context.Context, arg InsertDashaParams) (Dasha, error) {
	row := q.db.QueryRow(ctx, insertDasha,
		arg.ChartID,
		arg.System,
		arg.Planet,
		arg.StartDate,
		arg.EndDate,
		arg.Level,
		arg.ParentID,
		arg.Metadata,
	)
	var i Dasha
	err := row.Scan(
		&i.ID,
		&i.ChartID,
		&i.System,
		&i.Planet,
		&i.StartDate,
		&i.EndDate,
		&i.Level,
		&i.ParentID,
		&i.Metadata,
	)
	return i, err
}

const listActiveBirthProfiles = `-- name: ListActiveBirthProfiles :many
SELECT id, user_id, label, birth_date, birth_time, time_accuracy, birth_place, latitude, longitude, timezone, utc_offset_min, utc_instant, source, verified, version, superseded_by, is_active, created_at FROM birth_profiles
WHERE user_id = $1 AND is_active = TRUE
ORDER BY created_at
`

func (q *Queries) ListActiveBirthProfiles(ctx context.Context, userID pgtype.UUID) ([]BirthProfile, error) {
	rows, err := q.db.Query(ctx, listActiveBirthProfiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BirthProfile{}
	for rows.Next() {
		var i BirthProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.BirthDate,
			&i.BirthTime,
			&i.TimeAccuracy,
			&i.BirthPlace,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.UtcOffsetMin,
			&i.UtcInstant,
			&i.Source,
			&i.Verified,
			&i.Version,
			&i.SupersededBy,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBirthProfileVersions = `-- name: ListBirthProfileVersions :many
WITH RECURSIVE lineage AS (
    SELECT bp.id, bp.user_id, bp.label, bp.birth_date, bp.birth_time, bp.time_accuracy, bp.birth_place, bp.latitude, bp.longitude, bp.timezone, bp.utc_offset_min, bp.utc_instant, bp.source, bp.verified, bp.version, bp.superseded_by, bp.is_active, bp.created_at FROM birth_profiles bp
    WHERE bp.id = $1 AND bp.user_id = $2
  UNION ALL
    SELECT prev.id, prev.user_id, prev.label, prev.birth_date, prev.birth_time, prev.time_accuracy, prev.birth_place, prev.latitude, prev.longitude, prev.timezone, prev.utc_offset_min, prev.utc_instant, prev.source, prev.verified, prev.version, prev.superseded_by, prev.is_active, prev.created_at FROM birth_profiles prev
    JOIN lineage l ON prev.superseded_by = l.id
)
SELECT id, user_id, label, birth_date, birth_time, time_accuracy, birth_place, latitude, longitude, timezone, utc_offset_min, utc_instant, source, verified, version, superseded_by, is_active, created_at FROM lineage ORDER BY version DESC
`

type ListBirthProfileVersionsParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type ListBirthProfileVersionsRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Label        string
	BirthDate    pgtype.Date
	BirthTime    pgtype.Time
	TimeAccuracy string
	BirthPlace   string
	Latitude     float64
	Longitude    float64
	Timezone     string
	UtcOffsetMin int32
	UtcInstant   time.Time
	Source       string
	Verified     bool
	Version      int32
	SupersededBy pgtype.UUID
	IsActive     bool
	CreatedAt    time.Time
}

// The history behind one profile, newest first.
//
// Walks superseded_by BACKWARDS from the given id: each step finds the
// version that this one replaced. Callers ask for the history of the
// profile they are looking at, which is the active one, which is the
// newest — so walking back reaches every earlier version.
//
// Every column reference is qualified. An unqualified `id` here is
// ambiguous between the CTE and the table, and sqlc rejects it, which is
// the right moment to find out rather than at runtime.
func (q *Queries) ListBirthProfileVersions(ctx context.Context, arg ListBirthProfileVersionsParams) ([]ListBirthProfileVersionsRow, error) {
	rows, err := q.db.Query(ctx, listBirthProfileVersions, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBirthProfileVersionsRow{}
	for rows.Next() {
		var i ListBirthProfileVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.BirthDate,
			&i.BirthTime,
			&i.TimeAccuracy,
			&i.BirthPlace,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.UtcOffsetMin,
			&i.UtcInstant,
			&i.Source,
			&i.Verified,
			&i.Version,
			&i.SupersededBy,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChartsByEngineVersion = `-- name: ListChartsByEngineVersion :many
SELECT id, birth_profile_id, chart_type, calculation_system, ayanamsa, house_system, engine_version, chart_data, computed_at FROM charts
WHERE engine_version <> $1
ORDER BY computed_at
LIMIT $2
`

type ListChartsByEngineVersionParams struct {
	EngineVersion string
	Limit         int32
}

// Finds charts built by an older engine, so a library upgrade can be
// followed by a targeted recompute instead of a guess.
func (q *Queries) ListChartsByEngineVersion(ctx context.Context, arg ListChartsByEngineVersionParams) ([]Chart, error) {
	rows, err := q.db.Query(ctx, listChartsByEngineVersion, arg.EngineVersion, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chart{}
	for rows.Next() {
		var i Chart
		if err := rows.Scan(
			&i.ID,
			&i.BirthProfileID,
			&i.ChartType,
			&i.CalculationSystem,
			&i.Ayanamsa,
			&i.HouseSystem,
			&i.EngineVersion,
			&i.ChartData,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChartsForProfile = `-- name: ListChartsForProfile :many
SELECT c.id, c.birth_profile_id, c.chart_type, c.calculation_system, c.ayanamsa, c.house_system, c.engine_version, c.chart_data, c.computed_at FROM charts c
JOIN birth_profiles p ON p.id = c.birth_profile_id
WHERE c.birth_profile_id = $1 AND p.user_id = $2
ORDER BY c.chart_type
`

type ListChartsForProfileParams struct {
	BirthProfileID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) ListChartsForProfile(ctx context.Context, arg ListChartsForProfileParams) ([]Chart, error) {
	rows, err := q.db.Query(ctx, listChartsForProfile, arg.BirthProfileID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chart{}
	for rows.Next() {
		var i Chart
		if err := rows.Scan(
			&i.ID,
			&i.BirthProfileID,
			&i.ChartType,
			&i.CalculationSystem,
			&i.Ayanamsa,
			&i.HouseSystem,
			&i.EngineVersion,
			&i.ChartData,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashasByLevel = `-- name: ListDashasByLevel :many
SELECT d.id, d.chart_id, d.system, d.planet, d.start_date, d.end_date, d.level, d.parent_id, d.metadata FROM dashas d
JOIN charts c ON c.id = d.chart_id
JOIN birth_profiles p ON p.id = c.birth_profile_id
WHERE d.chart_id = $1 AND d.level = $2 AND p.user_id = $3
ORDER BY d.start_date
`

type ListDashasByLevelParams struct {
	ChartID pgtype.UUID
	Level   int16
	UserID  pgtype.UUID
}

func (q *Queries) ListDashasByLevel(ctx context.Context, arg ListDashasByLevelParams) ([]Dasha, error) {
	rows, err := q.db.Query(ctx, listDashasByLevel, arg.ChartID, arg.Level, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dasha{}
	for rows.Next() {
		var i Dasha
		if err := rows.Scan(
			&i.ID,
			&i.ChartID,
			&i.System,
			&i.Planet,
			&i.StartDate,
			&i.EndDate,
			&i.Level,
			&i.ParentID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransitsAt = `-- name: ListTransitsAt :many
SELECT DISTINCT ON (planet) id, planet, sign, degree, is_retrograde, timestamp, calculation_system, ayanamsa, metadata
FROM transits
WHERE timestamp <= $1 AND calculation_system = $2 AND ayanamsa = $3
ORDER BY planet, timestamp DESC
`

type ListTransitsAtParams struct {
	Timestamp         time.Time
	CalculationSystem string
	Ayanamsa          string
}

// Global and free of personal data, so no user scoping — and that is
// what makes them safe to cache across all users.
func (q *Queries) ListTransitsAt(ctx context.Context, arg ListTransitsAtParams) ([]Transit, error) {
	rows, err := q.db.Query(ctx, listTransitsAt, arg.Timestamp, arg.CalculationSystem, arg.Ayanamsa)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transit{}
	for rows.Next() {
		var i Transit
		if err := rows.Scan(
			&i.ID,
			&i.Planet,
			&i.Sign,
			&i.Degree,
			&i.IsRetrograde,
			&i.Timestamp,
			&i.CalculationSystem,
			&i.Ayanamsa,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlaces = `-- name: SearchPlaces :many

SELECT id, name, ascii_name, admin1, country_code, latitude, longitude, timezone, population FROM places
WHERE ascii_name ILIKE $1 || '%'
ORDER BY population DESC, ascii_name
LIMIT $2
`

type SearchPlacesParams struct {
	Column1 *string
	Limit   int32
}

// ─── places ──────────────────────────────────────────────────────────
// Prefix match, ranked by population — which is what makes "jaip"
// return Jaipur, Rajasthan rather than a village of 600 people. The
// ranking matters more than the matching at the highest drop-off point
// in the product.
func (q *Queries) SearchPlaces(ctx context.Context, arg SearchPlacesParams) ([]Place, error) {
	rows, err := q.db.Query(ctx, searchPlaces, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Place{}
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AsciiName,
			&i.Admin1,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.Population,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeBirthProfile = `-- name: SupersedeBirthProfile :one
UPDATE birth_profiles
SET superseded_by = $2, is_active = FALSE
WHERE id = $1 AND user_id = $3 AND is_active = TRUE
RETURNING id, user_id, label, birth_date, birth_time, time_accuracy, birth_place, latitude, longitude, timezone, utc_offset_min, utc_instant, source, verified, version, superseded_by, is_active, created_at
`

type SupersedeBirthProfileParams struct {
	ID           pgtype.UUID
	SupersededBy pgtype.UUID
	UserID       pgtype.UUID
}

// Marks a version replaced. Returns the row so the caller can tell
// "superseded it" from "there was nothing to supersede" without a second
// query — the same reason RevokeSession became :execrows in Phase 1.
func (q *Queries) SupersedeBirthProfile(ctx context.Context, arg SupersedeBirthProfileParams) (BirthProfile, error) {
	row := q.db.QueryRow(ctx, supersedeBirthProfile, arg.ID, arg.SupersededBy, arg.UserID)
	var i BirthProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.BirthDate,
		&i.BirthTime,
		&i.TimeAccuracy,
		&i.BirthPlace,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.UtcOffsetMin,
		&i.UtcInstant,
		&i.Source,
		&i.Verified,
		&i.Version,
		&i.SupersededBy,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const upsertChart = `-- name: UpsertChart :one

INSERT INTO charts (
    birth_profile_id, chart_type, calculation_system, ayanamsa,
    house_system, engine_version, chart_data
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (birth_profile_id, chart_type, calculation_system, ayanamsa, house_system)
DO UPDATE SET
    engine_version = EXCLUDED.engine_version,
    chart_data     = EXCLUDED.chart_data,
    computed_at    = now()
RETURNING id, birth_profile_id, chart_type, calculation_system, ayanamsa, house_system, engine_version, chart_data, computed_at
`

type UpsertChartParams struct {
	BirthProfileID    pgtype.UUID
	ChartType         string
	CalculationSystem string
	Ayanamsa          string
	HouseSystem       string
	EngineVersion     string
	ChartData         []byte
}

// ─── charts ──────────────────────────────────────────────────────────
// Keyed on every input that affects the output. Recomputing with the
// same inputs replaces the data in place; changing the ayanamsa creates
// a different row rather than overwriting an unrelated chart.
func (q *Queries) UpsertChart(ctx context.Context, arg UpsertChartParams) (Chart, error) {
	row := q.db.QueryRow(ctx, upsertChart,
		arg.BirthProfileID,
		arg.ChartType,
		arg.CalculationSystem,
		arg.Ayanamsa,
		arg.HouseSystem,
		arg.EngineVersion,
		arg.ChartData,
	)
	var i Chart
	err := row.Scan(
		&i.ID,
		&i.BirthProfileID,
		&i.ChartType,
		&i.CalculationSystem,
		&i.Ayanamsa,
		&i.HouseSystem,
		&i.EngineVersion,
		&i.ChartData,
		&i.ComputedAt,
	)
	return i, err
}

const upsertPlace = `-- name: UpsertPlace :exec
INSERT INTO places (id, name, ascii_name, admin1, country_code, latitude, longitude, timezone, population)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    name         = EXCLUDED.name,
    ascii_name   = EXCLUDED.ascii_name,
    admin1       = EXCLUDED.admin1,
    country_code = EXCLUDED.country_code,
    latitude     = EXCLUDED.latitude,
    longitude    = EXCLUDED.longitude,
    timezone     = EXCLUDED.timezone,
    population   = EXCLUDED.population
`

type UpsertPlaceParams struct {
	ID          int32
	Name        string
	AsciiName   string
	Admin1      *string
	CountryCode string
	Latitude    float64
	Longitude   float64
	Timezone    string
	Population  int32
}

// Keyed on the GeoNames id, so re-running the importer updates rows
// instead of duplicating them.
func (q *Queries) UpsertPlace(ctx context.Context, arg UpsertPlaceParams) error {
	_, err := q.db.Exec(ctx, upsertPlace,
		arg.ID,
		arg.Name,
		arg.AsciiName,
		arg.Admin1,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.Timezone,
		arg.Population,
	)
	return err
}

const upsertTransit = `-- name: UpsertTransit :one

INSERT INTO transits (planet, sign, degree, is_retrograde, timestamp, calculation_system, ayanamsa, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (planet, timestamp, calculation_system, ayanamsa)
DO UPDATE SET
    sign          = EXCLUDED.sign,
    degree        = EXCLUDED.degree,
    is_retrograde = EXCLUDED.is_retrograde,
    metadata      = EXCLUDED.metadata
RETURNING id, planet, sign, degree, is_retrograde, timestamp, calculation_system, ayanamsa, metadata
`

type UpsertTransitParams struct {
	Planet            string
	Sign              string
	Degree            float64
	IsRetrograde      bool
	Timestamp         time.Time
	CalculationSystem string
	Ayanamsa          string
	Metadata          []byte
}

// ─── transits ────────────────────────────────────────────────────────
func (q *Queries) UpsertTransit(ctx context.Context, arg UpsertTransitParams) (Transit, error) {
	row := q.db.QueryRow(ctx, upsertTransit,
		arg.Planet,
		arg.Sign,
		arg.Degree,
		arg.IsRetrograde,
		arg.Timestamp,
		arg.CalculationSystem,
		arg.Ayanamsa,
		arg.Metadata,
	)
	var i Transit
	err := row.Scan(
		&i.ID,
		&i.Planet,
		&i.Sign,
		&i.Degree,
		&i.IsRetrograde,
		&i.Timestamp,
		&i.CalculationSystem,
		&i.Ayanamsa,
		&i.Metadata,
	)
	return i, err
}
