// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelUserDeletion = `-- name: CancelUserDeletion :one
UPDATE users
SET deletion_requested_at = NULL, status = 'active', updated_at = now()
WHERE id = $1 AND deletion_requested_at IS NOT NULL
RETURNING id, email, email_verified, phone, phone_verified, name, gender, role, status, last_login_at, deletion_requested_at, created_at, updated_at
`

func (q *Queries) CancelUserDeletion(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, cancelUserDeletion, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Name,
		&i.Gender,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.DeletionRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDefaultPreferences = `-- name: CreateDefaultPreferences :one

INSERT INTO user_preferences (user_id) VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = user_preferences.user_id
RETURNING id, user_id, preferred_language, astrology_system, chart_style, theme, notification_preferences, communication_preferences
`

// ─── Preferences ─────────────────────────────────────────────────────
func (q *Queries) CreateDefaultPreferences(ctx context.Context, userID pgtype.UUID) (UserPreference, error) {
	row := q.db.QueryRow(ctx, createDefaultPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PreferredLanguage,
		&i.AstrologySystem,
		&i.ChartStyle,
		&i.Theme,
		&i.NotificationPreferences,
		&i.CommunicationPreferences,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id, family_id, refresh_hash, user_agent, ip_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, family_id, refresh_hash, user_agent, ip_hash, expires_at, used_at, revoked_at, created_at
`

type CreateSessionParams struct {
	UserID      pgtype.UUID
	FamilyID    pgtype.UUID
	RefreshHash []byte
	UserAgent   *string
	IpHash      []byte
	ExpiresAt   time.Time
}

// ─── Sessions ────────────────────────────────────────────────────────
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.FamilyID,
		arg.RefreshHash,
		arg.UserAgent,
		arg.IpHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshHash,
		&i.UserAgent,
		&i.IpHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserWithEmail = `-- name: CreateUserWithEmail :one
INSERT INTO users (email, email_verified) VALUES ($1, TRUE) RETURNING id, email, email_verified, phone, phone_verified, name, gender, role, status, last_login_at, deletion_requested_at, created_at, updated_at
`

func (q *Queries) CreateUserWithEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Name,
		&i.Gender,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.DeletionRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserWithPhone = `-- name: CreateUserWithPhone :one
INSERT INTO users (phone, phone_verified) VALUES ($1, TRUE) RETURNING id, email, email_verified, phone, phone_verified, name, gender, role, status, last_login_at, deletion_requested_at, created_at, updated_at
`

func (q *Queries) CreateUserWithPhone(ctx context.Context, phone *string) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Name,
		&i.Gender,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.DeletionRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now() - INTERVAL '30 days'
`

// Housekeeping for the worker. Expired rows prove nothing and grow
// forever.
func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const findIdentity = `-- name: FindIdentity :one

SELECT id, user_id, provider, provider_user_id, created_at FROM auth_identities WHERE provider = $1 AND provider_user_id = $2
`

type FindIdentityParams struct {
	Provider       AuthProvider
	ProviderUserID string
}

// ─── Identities ──────────────────────────────────────────────────────
func (q *Queries) FindIdentity(ctx context.Context, arg FindIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, findIdentity, arg.Provider, arg.ProviderUserID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const findSessionByHash = `-- name: FindSessionByHash :one
SELECT id, user_id, family_id, refresh_hash, user_agent, ip_hash, expires_at, used_at, revoked_at, created_at FROM sessions WHERE refresh_hash = $1
`

// Used only on the reuse path, to find which family to revoke. Deliberately
// ignores used_at/revoked_at: the whole point is to locate a token that
// has already been spent.
func (q *Queries) FindSessionByHash(ctx context.Context, refreshHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByHash, refreshHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshHash,
		&i.UserAgent,
		&i.IpHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one

SELECT id, email, email_verified, phone, phone_verified, name, gender, role, status, last_login_at, deletion_requested_at, created_at, updated_at FROM users WHERE email = $1 AND status <> 'deleted'
`

// Auth queries. See docs/specs/PHASE-01-AUTH-AND-USERS.md §3.
func (q *Queries) FindUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Name,
		&i.Gender,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.DeletionRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, email_verified, phone, phone_verified, name, gender, role, status, last_login_at, deletion_requested_at, created_at, updated_at FROM users WHERE id = $1 AND status <> 'deleted'
`

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Name,
		&i.Gender,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.DeletionRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByPhone = `-- name: FindUserByPhone :one
SELECT id, email, email_verified, phone, phone_verified, name, gender, role, status, last_login_at, deletion_requested_at, created_at, updated_at FROM users WHERE phone = $1 AND status <> 'deleted'
`

func (q *Queries) FindUserByPhone(ctx context.Context, phone *string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Name,
		&i.Gender,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.DeletionRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreferences = `-- name: GetPreferences :one
SELECT id, user_id, preferred_language, astrology_system, chart_style, theme, notification_preferences, communication_preferences FROM user_preferences WHERE user_id = $1
`

func (q *Queries) GetPreferences(ctx context.Context, userID pgtype.UUID) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PreferredLanguage,
		&i.AstrologySystem,
		&i.ChartStyle,
		&i.Theme,
		&i.NotificationPreferences,
		&i.CommunicationPreferences,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users WHERE id = $1
`

// Real deletion, not a flag. Every user-owned table declares ON DELETE
// CASCADE, so this removes the lot — which is what the Phase 1 gate
// means by "no row anywhere references the user".
//
// audit_logs is the deliberate exception: its user_id is not a foreign
// key, so the record that a deletion happened survives the deletion. It
// holds IDs and enums only, never PII.
func (q *Queries) HardDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteUser, id)
	return err
}

const linkIdentity = `-- name: LinkIdentity :one
INSERT INTO auth_identities (user_id, provider, provider_user_id)
VALUES ($1, $2, $3)
ON CONFLICT (provider, provider_user_id)
DO UPDATE SET user_id = auth_identities.user_id
RETURNING id, user_id, provider, provider_user_id, created_at
`

type LinkIdentityParams struct {
	UserID         pgtype.UUID
	Provider       AuthProvider
	ProviderUserID string
}

// ON CONFLICT DO UPDATE rather than DO NOTHING: DO NOTHING returns no
// row, so the caller cannot tell "already linked" from "insert failed"
// without a second query.
func (q *Queries) LinkIdentity(ctx context.Context, arg LinkIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, linkIdentity, arg.UserID, arg.Provider, arg.ProviderUserID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveDevices = `-- name: ListActiveDevices :many
SELECT DISTINCT ON (family_id) id, user_id, family_id, refresh_hash, user_agent, ip_hash, expires_at, used_at, revoked_at, created_at
FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY family_id, created_at DESC
`

// One row per DEVICE, not per session.
//
// A device is a family: every refresh issues a new session row sharing
// the family_id of the token it replaced, so a single browser open for an
// hour accumulates a dozen rows. Listing those as "devices" is both
// wrong and alarming — the user sees twelve unknown sign-ins — and
// revoking one of them kills a spent link in the chain rather than the
// device.
//
// DISTINCT ON takes the newest row per family, which carries the most
// recent user agent and expiry.
func (q *Queries) ListActiveDevices(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FamilyID,
			&i.RefreshHash,
			&i.UserAgent,
			&i.IpHash,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, user_id, family_id, refresh_hash, user_agent, ip_hash, expires_at, used_at, revoked_at, created_at FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

// Every row, including superseded links in a rotation chain. Used by the
// data export, where completeness is the point.
func (q *Queries) ListActiveSessions(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FamilyID,
			&i.RefreshHash,
			&i.UserAgent,
			&i.IpHash,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsForUser = `-- name: ListAuditLogsForUser :many
SELECT id, user_id, action, metadata, ip_hash, created_at FROM audit_logs WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListAuditLogsForUserParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) ListAuditLogsForUser(ctx context.Context, arg ListAuditLogsForUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Metadata,
			&i.IpHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesForUser = `-- name: ListIdentitiesForUser :many
SELECT id, user_id, provider, provider_user_id, created_at FROM auth_identities WHERE user_id = $1 ORDER BY created_at
`

// Needed by the data export. Without it the export declares an
// auth_identities field and always returns [], which is worse than
// omitting it: it tells the user there are none.
func (q *Queries) ListIdentitiesForUser(ctx context.Context, userID pgtype.UUID) ([]AuthIdentity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthIdentity{}
	for rows.Next() {
		var i AuthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPastDeletionGrace = `-- name: ListUsersPastDeletionGrace :many
SELECT id, email, email_verified, phone, phone_verified, name, gender, role, status, last_login_at, deletion_requested_at, created_at, updated_at FROM users
WHERE deletion_requested_at IS NOT NULL
  AND deletion_requested_at < $1
`

func (q *Queries) ListUsersPastDeletionGrace(ctx context.Context, deletionRequestedAt pgtype.Timestamptz) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersPastDeletionGrace, deletionRequestedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.PhoneVerified,
			&i.Name,
			&i.Gender,
			&i.Role,
			&i.Status,
			&i.LastLoginAt,
			&i.DeletionRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestUserDeletion = `-- name: RequestUserDeletion :one

UPDATE users
SET deletion_requested_at = now(), status = 'deleted', updated_at = now()
WHERE id = $1 AND deletion_requested_at IS NULL
RETURNING id, email, email_verified, phone, phone_verified, name, gender, role, status, last_login_at, deletion_requested_at, created_at, updated_at
`

// ─── Deletion ────────────────────────────────────────────────────────
func (q *Queries) RequestUserDeletion(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, requestUserDeletion, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Name,
		&i.Gender,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.DeletionRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeDeviceFamily = `-- name: RevokeDeviceFamily :execrows
UPDATE sessions SET revoked_at = now()
WHERE family_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeDeviceFamilyParams struct {
	FamilyID pgtype.UUID
	UserID   pgtype.UUID
}

// Signs one device out by ending its whole lineage.
//
// Scoped by user_id, so a caller cannot revoke another account's device
// even with a valid family id — the row count is what lets the handler
// answer 404 rather than a misleading 204.
func (q *Queries) RevokeDeviceFamily(ctx context.Context, arg RevokeDeviceFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDeviceFamily, arg.FamilyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// :execrows, not :exec. An :exec cannot distinguish "revoked it" from
// "matched nothing", so revoking someone else's session — which the
// user_id predicate correctly refuses — returned 204 and told the caller
// it had worked. The row count is what lets the handler answer 404.
func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
UPDATE sessions SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

// One leaked token invalidates every descendant of it. Cheap to run and
// it turns a silent compromise into a forced re-authentication.
func (q *Queries) RevokeTokenFamily(ctx context.Context, familyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, familyID)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE sessions
SET used_at = now()
WHERE refresh_hash = $1
  AND used_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, family_id, refresh_hash, user_agent, ip_hash, expires_at, used_at, revoked_at, created_at
`

// The single most important statement in this phase.
//
// Check and update in ONE statement. Two concurrent refreshes presenting
// the same token: Postgres serialises the UPDATE, so exactly one matches
// `used_at IS NULL` and gets a row back. The other gets no rows, which
// the caller treats as reuse and revokes the family.
//
// A read-then-write in Go would let both pass the check before either
// wrote — the classic TOCTOU that makes a leaked token usable twice. No
// application lock is needed, and a mocked database cannot test this.
func (q *Queries) RotateRefreshToken(ctx context.Context, refreshHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken, refreshHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshHash,
		&i.UserAgent,
		&i.IpHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchLastLogin = `-- name: TouchLastLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) TouchLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchLastLogin, id)
	return err
}

const updatePreferences = `-- name: UpdatePreferences :one
UPDATE user_preferences
SET preferred_language        = COALESCE($1, preferred_language),
    astrology_system          = COALESCE($2, astrology_system),
    chart_style               = COALESCE($3, chart_style),
    theme                     = COALESCE($4, theme),
    notification_preferences  = COALESCE($5, notification_preferences),
    communication_preferences = COALESCE($6, communication_preferences)
WHERE user_id = $7
RETURNING id, user_id, preferred_language, astrology_system, chart_style, theme, notification_preferences, communication_preferences
`

type UpdatePreferencesParams struct {
	PreferredLanguage        *string
	AstrologySystem          *string
	ChartStyle               *string
	Theme                    *string
	NotificationPreferences  []byte
	CommunicationPreferences []byte
	UserID                   pgtype.UUID
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, updatePreferences,
		arg.PreferredLanguage,
		arg.AstrologySystem,
		arg.ChartStyle,
		arg.Theme,
		arg.NotificationPreferences,
		arg.CommunicationPreferences,
		arg.UserID,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PreferredLanguage,
		&i.AstrologySystem,
		&i.ChartStyle,
		&i.Theme,
		&i.NotificationPreferences,
		&i.CommunicationPreferences,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name       = COALESCE($1, name),
    gender     = COALESCE($2, gender),
    updated_at = now()
WHERE id = $3 AND status <> 'deleted'
RETURNING id, email, email_verified, phone, phone_verified, name, gender, role, status, last_login_at, deletion_requested_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	Name   *string
	Gender *string
	ID     pgtype.UUID
}

// COALESCE so a PATCH omitting a field leaves it alone rather than
// nulling it. Only name and gender are writable here; email and phone
// change through a verification flow, never a profile edit.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.Name, arg.Gender, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Name,
		&i.Gender,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.DeletionRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const writeAuditLog = `-- name: WriteAuditLog :exec

INSERT INTO audit_logs (user_id, action, metadata, ip_hash)
VALUES ($1, $2, $3, $4)
`

type WriteAuditLogParams struct {
	UserID   pgtype.UUID
	Action   string
	Metadata []byte
	IpHash   []byte
}

// ─── Audit ───────────────────────────────────────────────────────────
func (q *Queries) WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) error {
	_, err := q.db.Exec(ctx, writeAuditLog,
		arg.UserID,
		arg.Action,
		arg.Metadata,
		arg.IpHash,
	)
	return err
}
