// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendMessage = `-- name: AppendMessage :one

WITH owned AS (
    UPDATE conversations
    SET message_count = message_count + 1,
        updated_at = now()
    WHERE conversations.id = $12
      AND conversations.user_id = $13
    RETURNING id AS owned_conversation_id
)
INSERT INTO messages (
    conversation_id, role, content, intent, model, provider_id,
    prompt_version, input_tokens, output_tokens, latency_ms,
    is_partial, safety_flags
)
SELECT owned.owned_conversation_id,
       $1,
       $2,
       $3,
       $4,
       $5,
       $6,
       $7,
       $8,
       $9,
       $10,
       -- COALESCE because naming the column in the INSERT list above
       -- disables its DEFAULT. Without it, a caller that has no flags to
       -- record passes a nil slice, which reaches Postgres as NULL and
       -- fails the column's NOT NULL — a failure in the ordinary path,
       -- not the exceptional one. '[]' is the same value the column
       -- defaults to: "none fired", which is a different claim from
       -- "we hold nothing".
       COALESCE($11::jsonb, '[]'::jsonb)
FROM owned
RETURNING messages.id, messages.conversation_id, messages.role,
          messages.content, messages.intent, messages.model,
          messages.provider_id, messages.prompt_version,
          messages.input_tokens, messages.output_tokens, messages.latency_ms,
          messages.is_partial, messages.safety_flags, messages.is_reported,
          messages.created_at
`

type AppendMessageParams struct {
	Role           string
	Content        string
	Intent         *string
	Model          *string
	ProviderID     *string
	PromptVersion  *string
	InputTokens    *int32
	OutputTokens   *int32
	LatencyMs      *int32
	IsPartial      bool
	SafetyFlags    []byte
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}

type AppendMessageRow struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Content        string
	Intent         *string
	Model          *string
	ProviderID     *string
	PromptVersion  *string
	InputTokens    *int32
	OutputTokens   *int32
	LatencyMs      *int32
	IsPartial      bool
	SafetyFlags    []byte
	IsReported     bool
	CreatedAt      time.Time
}

// ─── messages: append ────────────────────────────────────────────────
// One turn, and the conversation's counter, in a single statement.
//
// ── Why the UPDATE is the CTE and the INSERT is the main statement ──
//
// The UPDATE is the authorisation. It matches nothing for a non-owner,
// so `owned` is empty, so the INSERT's SELECT produces no row and no
// message is written — the same "no row rather than a row the caller is
// trusted to inspect" shape as the rest of this file, applied to a
// write. Appending to somebody else's conversation is not merely
// refused; it is unrepresentable.
//
// It is also what keeps `message_count` honest. One statement means the
// counter and the row land together or not at all: a CHECK violation on
// the message rolls the increment back with it, and the increment cannot
// happen without a message because the INSERT is what consumes `owned`.
//
// Concurrency: `message_count + 1` is re-evaluated after the row lock
// the UPDATE takes, so two simultaneous appends serialise and neither
// increment is lost. No explicit `FOR UPDATE` is needed — that is for
// read-then-write sequences (balances, Phase 7), not for a counter
// incremented in terms of itself.
//
// ── Why not a trigger ──
//
// A trigger on `messages` is the reflex and it is a trap here. An
// AFTER DELETE trigger decrementing the counter would fire for every
// message during a conversation's `ON DELETE CASCADE` and try to UPDATE
// the `conversations` row that is itself being deleted. That either
// errors or silently does nothing depending on trigger timing, and the
// failure appears at account deletion — the one path that must not have
// surprises. The cascade needs no decrement, because the counter is
// deleted along with the row that holds it.
// ── Two pieces of sqlc pedantry, both load-bearing ──
//
// The predicate columns are table-qualified and the CTE's output column
// is aliased. Postgres accepts the unqualified, unaliased version
// without complaint; sqlc's analyser resolves names across the whole
// statement, sees `id` on both `conversations` and `messages`, and fails
// the build with `column reference "id" is ambiguous` — reported at a
// line several statements further down, which is not a hint worth
// rediscovering.
func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (AppendMessageRow, error) {
	row := q.db.QueryRow(ctx, appendMessage,
		arg.Role,
		arg.Content,
		arg.Intent,
		arg.Model,
		arg.ProviderID,
		arg.PromptVersion,
		arg.InputTokens,
		arg.OutputTokens,
		arg.LatencyMs,
		arg.IsPartial,
		arg.SafetyFlags,
		arg.ConversationID,
		arg.UserID,
	)
	var i AppendMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Intent,
		&i.Model,
		&i.ProviderID,
		&i.PromptVersion,
		&i.InputTokens,
		&i.OutputTokens,
		&i.LatencyMs,
		&i.IsPartial,
		&i.SafetyFlags,
		&i.IsReported,
		&i.CreatedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one



INSERT INTO conversations (user_id, birth_profile_id, title, category, persona)
SELECT p.user_id,
       p.id,
       $1,
       $2,
       $3
FROM birth_profiles p
WHERE p.id = $4
  AND p.user_id = $5
  AND p.is_active
RETURNING id, user_id, birth_profile_id, title, category, persona, message_count, is_archived, created_at, updated_at
`

type CreateConversationParams struct {
	Title          *string
	Category       *string
	Persona        string
	BirthProfileID pgtype.UUID
	UserID         pgtype.UUID
}

// Conversation, message and context queries. PHASE-05 task 5.10.
//
// ── Every read is scoped by user_id in the SQL ──
//
// Not in the handler. `shares.sql` put it this way and it is worth
// repeating because this file is where it matters most: "a predicate in
// the query is a guarantee the handler cannot forget to apply."
//
// `.claude/rules/security.md`: "Cross-user access returns 404, not 403 —
// a 403 confirms the resource exists." A query that returned the row and
// left the ownership decision to Go would make that guarantee depend on
// every future call site remembering to check — including the ones added
// by tasks 5.12, 5.16 and 5.17, by someone who has not read this
// comment. Scoped in the SQL, a non-owner's request produces NO ROW,
// `pgx.ErrNoRows`, and a 404 that cannot accidentally become a 403.
//
// The writes are scoped the same way, which matters more: a rename or an
// archive that affected somebody else's row would be a silent
// cross-account mutation, not merely an information leak.
//
// ── Why the message queries name their columns ──
//
// `messages.search_tsv` is a GENERATED tsvector — index payload, not
// data. `SELECT *` would carry it over the wire on every message read,
// into a Go field no code in this service can use (sqlc types tsvector
// as `interface{}`). The column lists below are therefore explicit and
// identical, in schema order:
//
//	id, conversation_id, role, content, intent, model, provider_id,
//	prompt_version, input_tokens, output_tokens, latency_ms, is_partial,
//	safety_flags, is_reported, created_at
//
// `conversations` and `message_contexts` have no generated column, so
// they use `*`.
// ─── conversations: create ───────────────────────────────────────────
// Start a thread against one of the caller's own birth profiles.
//
// INSERT ... SELECT rather than INSERT ... VALUES, and that is the whole
// point of this query. `birth_profile_id` arrives from the client, so
// VALUES would happily open a conversation bound to another user's
// chart — §12's first checklist item ("chart context comes from the
// chart Go loaded after an ownership check — never from an ID in the
// message body") lost at the moment the thread is created rather than
// when it is read.
//
// Selecting the row makes the profile's ownership the precondition for
// the insert: a foreign profile matches nothing, no row is inserted, and
// the caller gets `pgx.ErrNoRows` → 404.
//
// `user_id` is taken from the profile row, not from the parameter, so
// the two cannot disagree. The parameter only narrows.
//
// `is_active` is required too. Correcting a birth time supersedes the
// old profile (000003), and a NEW thread started on a superseded
// version would be read against a chart its owner has already said was
// wrong. Existing threads keep pointing at it — that is the audit trail
// — but nothing new attaches to it.
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.Title,
		arg.Category,
		arg.Persona,
		arg.BirthProfileID,
		arg.UserID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthProfileID,
		&i.Title,
		&i.Category,
		&i.Persona,
		&i.MessageCount,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :execrows
DELETE FROM conversations
WHERE id = $1 AND user_id = $2
`

type DeleteConversationParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Scoped by user. `:execrows` rather than `:exec` so the handler can
// tell "deleted" from "not yours or not there" and return 404 for both
// — the two cases must be indistinguishable to the client.
//
// The messages and their contexts go with it, by `ON DELETE CASCADE` in
// migration 000009 rather than by two more statements here. §16 gates on
// it ("Deleting a conversation cascades to messages and contexts") and
// the database is the only place that cannot forget.
func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConversation, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConversation = `-- name: GetConversation :one

SELECT id, user_id, birth_profile_id, title, category, persona, message_count, is_archived, created_at, updated_at FROM conversations
WHERE id = $1 AND user_id = $2
`

type GetConversationParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// ─── conversations: read ─────────────────────────────────────────────
// One thread, for its owner.
//
// Archived threads are included: §7's history screen can open one, and
// "archived" means "not in the default list", not "gone".
func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthProfileID,
		&i.Title,
		&i.Category,
		&i.Persona,
		&i.MessageCount,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageContext = `-- name: GetMessageContext :one
SELECT mc.id, mc.message_id, mc.astrology_context, mc.fact_index, mc.knowledge_chunk_ids, mc.prompt_version, mc.context_version, mc.created_at FROM message_contexts mc
JOIN messages m ON m.id = mc.message_id
JOIN conversations c ON c.id = m.conversation_id
WHERE mc.message_id = $1
  AND c.user_id = $2
`

type GetMessageContextParams struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
}

// The "Why am I seeing this?" payload (§7), and §16's "renders the real
// stored context".
//
// A read, not a regeneration. Rebuilding the context from the chart
// would use today's context builder against today's corpus and answer a
// different question — "what would we retrieve now?" — while looking
// like it answered the original one. Task 5.5's dimension migration
// re-embeds the whole corpus, and re-chunking changes which chunk ids
// exist at all, so the regenerated answer would drift without anything
// appearing to change.
//
// Two joins to reach `user_id`: contexts hang off messages, which hang
// off conversations, which is where ownership lives. The alternative —
// trusting the handler to have loaded the conversation first — is the
// thing this file refuses to do.
func (q *Queries) GetMessageContext(ctx context.Context, arg GetMessageContextParams) (MessageContext, error) {
	row := q.db.QueryRow(ctx, getMessageContext, arg.MessageID, arg.UserID)
	var i MessageContext
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.AstrologyContext,
		&i.FactIndex,
		&i.KnowledgeChunkIds,
		&i.PromptVersion,
		&i.ContextVersion,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessageContext = `-- name: InsertMessageContext :one

INSERT INTO message_contexts (
    message_id, astrology_context, fact_index, knowledge_chunk_ids,
    prompt_version, context_version
)
SELECT m.id,
       $1,
       $2,
       $3,
       m.prompt_version,
       $4
FROM messages m
WHERE m.id = $5
RETURNING id, message_id, astrology_context, fact_index, knowledge_chunk_ids, prompt_version, context_version, created_at
`

type InsertMessageContextParams struct {
	AstrologyContext  []byte
	FactIndex         []byte
	KnowledgeChunkIds []byte
	ContextVersion    string
	MessageID         pgtype.UUID
}

// ─── message_contexts ────────────────────────────────────────────────
// What was supplied to the model for one assistant message.
//
// `prompt_version` is NOT a parameter. It is selected off the message
// row, so the copy here and the copy on `messages` cannot disagree —
// the duplication §5 implies becomes a derivation. A message with no
// `prompt_version` fails the NOT NULL and the insert errors loudly,
// which is correct: a context row for a response that does not record
// which prompt produced it cannot explain that response.
//
// INSERT ... SELECT also makes a context for a non-existent message
// return no row rather than a foreign-key error, matching the shape of
// every other write in this file.
//
// Not scoped by user, and that is deliberate — this runs inside the
// chat pipeline, immediately after `AppendMessage` returned the message
// it is about, in the same request. There is no client-supplied id to
// validate. The scoping lives on the READ, below, which is where a
// client-supplied id does arrive.
func (q *Queries) InsertMessageContext(ctx context.Context, arg InsertMessageContextParams) (MessageContext, error) {
	row := q.db.QueryRow(ctx, insertMessageContext,
		arg.AstrologyContext,
		arg.FactIndex,
		arg.KnowledgeChunkIds,
		arg.ContextVersion,
		arg.MessageID,
	)
	var i MessageContext
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.AstrologyContext,
		&i.FactIndex,
		&i.KnowledgeChunkIds,
		&i.PromptVersion,
		&i.ContextVersion,
		&i.CreatedAt,
	)
	return i, err
}

const listAllConversationsForUser = `-- name: ListAllConversationsForUser :many
SELECT id, user_id, birth_profile_id, title, category, persona, message_count, is_archived, created_at, updated_at FROM conversations
WHERE user_id = $1
ORDER BY created_at
`

// Every thread, archived or not, uncapped — for the data export.
//
// Uncapped on purpose, like `ListChartSharesForUser`. A portability
// export that silently drops the tail is the failure
// `internal/users/export.go` exists to prevent: the user reads an absent
// row as "I never had that conversation".
func (q *Queries) ListAllConversationsForUser(ctx context.Context, userID pgtype.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listAllConversationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BirthProfileID,
			&i.Title,
			&i.Category,
			&i.Persona,
			&i.MessageCount,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedConversations = `-- name: ListArchivedConversations :many
SELECT id, user_id, birth_profile_id, title, category, persona, message_count, is_archived, created_at, updated_at FROM conversations
WHERE user_id = $1 AND is_archived = TRUE
ORDER BY updated_at DESC
LIMIT $2
`

type ListArchivedConversationsParams struct {
	UserID pgtype.UUID
	Limit  int32
}

// The archive, as its own list rather than a flag on the one above.
func (q *Queries) ListArchivedConversations(ctx context.Context, arg ListArchivedConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listArchivedConversations, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BirthProfileID,
			&i.Title,
			&i.Category,
			&i.Persona,
			&i.MessageCount,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT id, user_id, birth_profile_id, title, category, persona, message_count, is_archived, created_at, updated_at FROM conversations
WHERE user_id = $1 AND is_archived = FALSE
ORDER BY updated_at DESC
LIMIT $2
`

type ListConversationsParams struct {
	UserID pgtype.UUID
	Limit  int32
}

// The history screen's default list: this user's live threads, most
// recently active first.
//
// `is_archived = FALSE` is spelled out rather than parameterised. A
// single query with `is_archived = $2` would read as tidier and would
// defeat `conversations_user_active_idx`, which is partial precisely
// because this is the query that runs on every history load.
func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BirthProfileID,
			&i.Title,
			&i.Category,
			&i.Persona,
			&i.MessageCount,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many

SELECT m.id, m.conversation_id, m.role, m.content, m.intent, m.model,
       m.provider_id, m.prompt_version, m.input_tokens, m.output_tokens,
       m.latency_ms, m.is_partial, m.safety_flags, m.is_reported, m.created_at
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE m.conversation_id = $1
  AND c.user_id = $2
ORDER BY m.created_at, m.id
`

type ListMessagesParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}

type ListMessagesRow struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Content        string
	Intent         *string
	Model          *string
	ProviderID     *string
	PromptVersion  *string
	InputTokens    *int32
	OutputTokens   *int32
	LatencyMs      *int32
	IsPartial      bool
	SafetyFlags    []byte
	IsReported     bool
	CreatedAt      time.Time
}

// ─── messages: read ──────────────────────────────────────────────────
// One conversation's turns, oldest first, for its owner.
//
// The join is the ownership check. `conversation_id` alone would return
// the whole of somebody else's thread to anyone who learned its id,
// which is the single worst read in this product: it is the complete
// text of what a person asked about their health and their marriage.
//
// `id` is the tiebreaker on `created_at`. `now()` is the transaction's
// start time, so two messages written in one transaction share a
// timestamp exactly; a random UUID is not a meaningful order but it is a
// STABLE one, which is what keeps a paginated list from repeating or
// skipping a row. In normal operation the user's turn and the
// assistant's are seconds apart (§6 persists the user message before the
// model is called), so the tiebreaker is a guard, not the usual path.
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Intent,
			&i.Model,
			&i.ProviderID,
			&i.PromptVersion,
			&i.InputTokens,
			&i.OutputTokens,
			&i.LatencyMs,
			&i.IsPartial,
			&i.SafetyFlags,
			&i.IsReported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesForUser = `-- name: ListMessagesForUser :many
SELECT m.id, m.conversation_id, m.role, m.content, m.intent, m.model,
       m.provider_id, m.prompt_version, m.input_tokens, m.output_tokens,
       m.latency_ms, m.is_partial, m.safety_flags, m.is_reported, m.created_at
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE c.user_id = $1
ORDER BY m.created_at, m.id
LIMIT $2
`

type ListMessagesForUserParams struct {
	UserID pgtype.UUID
	Limit  int32
}

type ListMessagesForUserRow struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Content        string
	Intent         *string
	Model          *string
	ProviderID     *string
	PromptVersion  *string
	InputTokens    *int32
	OutputTokens   *int32
	LatencyMs      *int32
	IsPartial      bool
	SafetyFlags    []byte
	IsReported     bool
	CreatedAt      time.Time
}

// Every message this person has, across every conversation — the data
// export.
//
// Capped, unlike the conversation list, and the asymmetry is deliberate:
// a long-lived account has tens of thousands of messages and a response
// that times out is not an export. The audit log is capped for the same
// reason in `internal/users/export.go`. Ordered oldest-first so a
// truncated export is a truncated BEGINNING of the history rather than
// an arbitrary slice.
func (q *Queries) ListMessagesForUser(ctx context.Context, arg ListMessagesForUserParams) ([]ListMessagesForUserRow, error) {
	rows, err := q.db.Query(ctx, listMessagesForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesForUserRow{}
	for rows.Next() {
		var i ListMessagesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Intent,
			&i.Model,
			&i.ProviderID,
			&i.PromptVersion,
			&i.InputTokens,
			&i.OutputTokens,
			&i.LatencyMs,
			&i.IsPartial,
			&i.SafetyFlags,
			&i.IsReported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT m.id, m.conversation_id, m.role, m.content, m.intent, m.model,
       m.provider_id, m.prompt_version, m.input_tokens, m.output_tokens,
       m.latency_ms, m.is_partial, m.safety_flags, m.is_reported, m.created_at
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE m.conversation_id = $1
  AND c.user_id = $2
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3
`

type ListRecentMessagesParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
	Limit          int32
}

type ListRecentMessagesRow struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Content        string
	Intent         *string
	Model          *string
	ProviderID     *string
	PromptVersion  *string
	InputTokens    *int32
	OutputTokens   *int32
	LatencyMs      *int32
	IsPartial      bool
	SafetyFlags    []byte
	IsReported     bool
	CreatedAt      time.Time
}

// The last N turns, for §5's context window (`CHAT_RECENT_MESSAGE_WINDOW`).
//
// Newest first, because "the last 6" has to be taken from the recent end
// — the caller reverses them before building the prompt. Ordering
// ascending with a LIMIT would return the OLDEST six, which is the
// version of this query that looks right and produces a model with no
// idea what was just said.
//
// Partial messages are included. A disconnect mid-answer is part of the
// thread the user can see, and omitting it from the context would make
// the model's next turn contradict the screen.
func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]ListRecentMessagesRow, error) {
	rows, err := q.db.Query(ctx, listRecentMessages, arg.ConversationID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentMessagesRow{}
	for rows.Next() {
		var i ListRecentMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Intent,
			&i.Model,
			&i.ProviderID,
			&i.PromptVersion,
			&i.InputTokens,
			&i.OutputTokens,
			&i.LatencyMs,
			&i.IsPartial,
			&i.SafetyFlags,
			&i.IsReported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageReported = `-- name: MarkMessageReported :execrows
UPDATE messages m
SET is_reported = TRUE
WHERE m.id = $1
  AND EXISTS (
      SELECT 1 FROM conversations c
      WHERE c.id = m.conversation_id AND c.user_id = $2
  )
`

type MarkMessageReportedParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// §7's Report button (task 5.17).
//
// Scoped by owner through the conversation, so a user can only report an
// answer given to them. Without the join, any message id would be
// reportable by anyone — a way to flood the review queue with other
// people's conversations.
//
// Idempotent: reporting twice sets a boolean that is already true.
// `:execrows` returns 0 for a message that is not this user's, which the
// handler turns into 404.
func (q *Queries) MarkMessageReported(ctx context.Context, arg MarkMessageReportedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMessageReported, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameConversation = `-- name: RenameConversation :one

UPDATE conversations
SET title = $1
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, birth_profile_id, title, category, persona, message_count, is_archived, created_at, updated_at
`

type RenameConversationParams struct {
	Title  *string
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// ─── conversations: update and delete ────────────────────────────────
// Scoped by user, so renaming somebody else's thread affects no row and
// the handler answers 404 — never 403, which would confirm it exists.
//
// `updated_at` is deliberately NOT touched. It is the history sort key
// and it means "when did this conversation last have something said in
// it"; a rename would otherwise shuffle a year-old thread to the top of
// the list for a cosmetic edit.
func (q *Queries) RenameConversation(ctx context.Context, arg RenameConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, renameConversation, arg.Title, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthProfileID,
		&i.Title,
		&i.Category,
		&i.Persona,
		&i.MessageCount,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchMessages = `-- name: SearchMessages :many
SELECT m.id, m.conversation_id, m.role, m.content, m.intent, m.model,
       m.provider_id, m.prompt_version, m.input_tokens, m.output_tokens,
       m.latency_ms, m.is_partial, m.safety_flags, m.is_reported, m.created_at,
       c.title AS conversation_title,
       ts_rank(m.search_tsv, websearch_to_tsquery('english', $1)) AS rank
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE c.user_id = $2
  AND m.search_tsv @@ websearch_to_tsquery('english', $1)
ORDER BY rank DESC, m.created_at DESC
LIMIT $3
`

type SearchMessagesParams struct {
	Query  string
	UserID pgtype.UUID
	Limit  int32
}

type SearchMessagesRow struct {
	ID                pgtype.UUID
	ConversationID    pgtype.UUID
	Role              string
	Content           string
	Intent            *string
	Model             *string
	ProviderID        *string
	PromptVersion     *string
	InputTokens       *int32
	OutputTokens      *int32
	LatencyMs         *int32
	IsPartial         bool
	SafetyFlags       []byte
	IsReported        bool
	CreatedAt         time.Time
	ConversationTitle *string
	Rank              float32
}

// Full-text search across one user's own history (§7, task 5.16).
//
// Scoped by `c.user_id` in the same WHERE clause as the match, so a
// search can only ever rank this person's own text. A search endpoint is
// the easiest place in a product to leak the whole corpus of user
// content, because the predicate that limits it looks like a filter
// rather than like authorisation.
//
// `websearch_to_tsquery` rather than `plainto_tsquery`: it accepts what
// people actually type into a search box — quoted phrases, `or`, a
// leading `-` to exclude — and, unlike `to_tsquery`, it cannot raise a
// syntax error on user input. A search that 500s on an apostrophe is a
// search nobody uses twice.
//
// The query text is matched against `search_tsv`, the generated column,
// so `messages_search_idx` serves it. `ts_rank` recomputes over the
// matched rows only, which is a user-sized set, not a corpus-sized one.
//
// `conversation_title` comes along because a search hit is useless
// without the thread it belongs to — the UI needs somewhere to send the
// tap.
func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages, arg.Query, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesRow{}
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Intent,
			&i.Model,
			&i.ProviderID,
			&i.PromptVersion,
			&i.InputTokens,
			&i.OutputTokens,
			&i.LatencyMs,
			&i.IsPartial,
			&i.SafetyFlags,
			&i.IsReported,
			&i.CreatedAt,
			&i.ConversationTitle,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationArchived = `-- name: SetConversationArchived :one
UPDATE conversations
SET is_archived = $1
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, birth_profile_id, title, category, persona, message_count, is_archived, created_at, updated_at
`

type SetConversationArchivedParams struct {
	IsArchived bool
	ID         pgtype.UUID
	UserID     pgtype.UUID
}

// Archive or restore. One query for both directions, because a toggle
// implemented as two endpoints drifts.
//
// `updated_at` untouched, same reasoning as the rename.
func (q *Queries) SetConversationArchived(ctx context.Context, arg SetConversationArchivedParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, setConversationArchived, arg.IsArchived, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthProfileID,
		&i.Title,
		&i.Category,
		&i.Persona,
		&i.MessageCount,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
