// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package dbgen

import (
	"context"
)

// iteratorForBulkInsertDashas implements pgx.CopyFromSource.
type iteratorForBulkInsertDashas struct {
	rows                 []BulkInsertDashasParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertDashas) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertDashas) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ChartID,
		r.rows[0].System,
		r.rows[0].Planet,
		r.rows[0].StartDate,
		r.rows[0].EndDate,
		r.rows[0].Level,
		r.rows[0].ParentID,
		r.rows[0].Metadata,
	}, nil
}

func (r iteratorForBulkInsertDashas) Err() error {
	return nil
}

// The whole tree in ONE round trip.
//
// 819 rows per chart — 9 mahadashas, 81 antardashas, 729
// pratyantardashas — inserted one at a time was 819 round trips inside
// the transaction, and measured as the dominant cost of a cold chart
// request: 564 ms against a 350 ms budget. COPY makes it one.
//
// `id` is supplied by the caller rather than defaulted, because a child
// row needs its parent's id BEFORE either is written. Generating the
// UUIDs in Go is what makes a single batch possible at all.
//
// Rows must arrive parents-first: the parent_id foreign key is checked
// per row, so a level-2 row ahead of its level-1 parent is rejected. A
// breadth-first flatten gives that ordering for free.
func (q *Queries) BulkInsertDashas(ctx context.Context, arg []BulkInsertDashasParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"dashas"}, []string{"id", "chart_id", "system", "planet", "start_date", "end_date", "level", "parent_id", "metadata"}, &iteratorForBulkInsertDashas{rows: arg})
}
