// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countKnowledgeCorpus = `-- name: CountKnowledgeCorpus :one

SELECT
    (SELECT count(*) FROM knowledge_documents WHERE is_active) AS documents,
    (SELECT count(*) FROM knowledge_chunks)                    AS chunks,
    (SELECT count(*) FROM knowledge_chunks
      WHERE embedding IS NULL)                                 AS unembedded,
    (SELECT count(DISTINCT embedding_model) FROM knowledge_chunks) AS embedding_models
`

type CountKnowledgeCorpusRow struct {
	Documents       int64
	Chunks          int64
	Unembedded      int64
	EmbeddingModels int64
}

// ─── Operational checks ──────────────────────────────────────────────
// The two numbers the phase gate asks for (§16: ≥400 documents, chunked,
// embedded) plus the one that says whether it is sound.
//
// `unembedded` reads through `kc_unembedded_idx`, a partial index on
// `embedding IS NULL`. In a healthy corpus it is empty, which is the
// point: an unembedded chunk is invisible to vector search while still
// matching keyword search, and that half-presence reads as a ranking
// mystery rather than as missing data.
func (q *Queries) CountKnowledgeCorpus(ctx context.Context) (CountKnowledgeCorpusRow, error) {
	row := q.db.QueryRow(ctx, countKnowledgeCorpus)
	var i CountKnowledgeCorpusRow
	err := row.Scan(
		&i.Documents,
		&i.Chunks,
		&i.Unembedded,
		&i.EmbeddingModels,
	)
	return i, err
}

const deleteKnowledgeChunks = `-- name: DeleteKnowledgeChunks :execrows
DELETE FROM knowledge_chunks WHERE document_id = $1
`

// Clear a document's chunks before re-inserting them.
//
// Replace rather than upsert, because re-chunking can produce a DIFFERENT
// NUMBER of chunks. An upsert keyed on (document_id, chunk_index) would
// leave the tail of the previous run behind — orphan chunks at indexes the
// new run never reached, still matching keyword search, still being
// retrieved. They would be the only chunks in the corpus whose text no
// authored file contains.
func (q *Queries) DeleteKnowledgeChunks(ctx context.Context, documentID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteKnowledgeChunks, documentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getKnowledgeDocumentChecksum = `-- name: GetKnowledgeDocumentChecksum :one
SELECT d.source_checksum,
       (SELECT count(*) FROM knowledge_chunks c WHERE c.document_id = d.id) AS chunk_count
FROM knowledge_documents d
WHERE d.title = $1 AND d.language = $2 AND d.version = $3
`

type GetKnowledgeDocumentChecksumParams struct {
	Title    string
	Language string
	Version  int32
}

type GetKnowledgeDocumentChecksumRow struct {
	SourceChecksum string
	ChunkCount     int64
}

// What the database already holds for this identity.
//
// Returns the checksum and the chunk count together because both have to
// match before a re-run can skip a document. A matching checksum with
// zero chunks is a previous run that failed between the document insert
// and the chunk inserts — and skipping that leaves a document in the
// corpus with nothing retrievable in it.
func (q *Queries) GetKnowledgeDocumentChecksum(ctx context.Context, arg GetKnowledgeDocumentChecksumParams) (GetKnowledgeDocumentChecksumRow, error) {
	row := q.db.QueryRow(ctx, getKnowledgeDocumentChecksum, arg.Title, arg.Language, arg.Version)
	var i GetKnowledgeDocumentChecksumRow
	err := row.Scan(&i.SourceChecksum, &i.ChunkCount)
	return i, err
}

const insertKnowledgeChunk = `-- name: InsertKnowledgeChunk :exec
INSERT INTO knowledge_chunks (
    document_id, content, chunk_index, token_count, embedding, embedding_model, metadata
) VALUES (
    $1, $2, $3, $4,
    $5::vector, $6, $7
)
`

type InsertKnowledgeChunkParams struct {
	DocumentID     pgtype.UUID
	Content        string
	ChunkIndex     int32
	TokenCount     int32
	Embedding      string
	EmbeddingModel string
	Metadata       []byte
}

// One chunk, with its vector.
//
// See the note at the top of this file for why the vector is a string
// here and cast in the SQL.
func (q *Queries) InsertKnowledgeChunk(ctx context.Context, arg InsertKnowledgeChunkParams) error {
	_, err := q.db.Exec(ctx, insertKnowledgeChunk,
		arg.DocumentID,
		arg.Content,
		arg.ChunkIndex,
		arg.TokenCount,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.Metadata,
	)
	return err
}

const listKnowledgeChecksums = `-- name: ListKnowledgeChecksums :many
SELECT title, language, version, source_checksum
FROM knowledge_documents
ORDER BY title, language, version
`

type ListKnowledgeChecksumsRow struct {
	Title          string
	Language       string
	Version        int32
	SourceChecksum string
}

// Every stored document's identity and checksum, for verifying the corpus
// against what is on disk.
func (q *Queries) ListKnowledgeChecksums(ctx context.Context) ([]ListKnowledgeChecksumsRow, error) {
	rows, err := q.db.Query(ctx, listKnowledgeChecksums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKnowledgeChecksumsRow{}
	for rows.Next() {
		var i ListKnowledgeChecksumsRow
		if err := rows.Scan(
			&i.Title,
			&i.Language,
			&i.Version,
			&i.SourceChecksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertKnowledgeDocument = `-- name: UpsertKnowledgeDocument :one


INSERT INTO knowledge_documents (
    title, category, content, language, source,
    authority, astrology_system, metadata, source_checksum
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (title, language, version) DO UPDATE SET
    category         = EXCLUDED.category,
    content          = EXCLUDED.content,
    source           = EXCLUDED.source,
    authority        = EXCLUDED.authority,
    astrology_system = EXCLUDED.astrology_system,
    metadata         = EXCLUDED.metadata,
    source_checksum  = EXCLUDED.source_checksum,
    is_active        = TRUE,
    updated_at       = now()
RETURNING id, title, category, content, language, source, authority, astrology_system, metadata, is_active, version, created_at, updated_at, source_checksum
`

type UpsertKnowledgeDocumentParams struct {
	Title           string
	Category        string
	Content         string
	Language        string
	Source          string
	Authority       int16
	AstrologySystem string
	Metadata        []byte
	SourceChecksum  string
}

// Knowledge-base queries. PHASE-05 tasks 5.1 and 5.4.
//
// Written by `cmd/ingest-kb` only. `ai-service` reads these tables as
// `astro_ro` through asyncpg (task 5.6) rather than through here — the
// single-writer rule means Go owns the writes, not that Go owns every
// read.
//
// ── Why the embedding is a string in Go ──
//
// Left to itself, sqlc maps `vector(768)` to `*pgvector.Vector` and pulls
// in github.com/pgvector/pgvector-go — a new direct dependency that also
// has to be registered with every pgx pool before the type encodes. It is
// overridden to `string` in sqlc.yaml, and the vector travels as
// pgvector's own documented text form, `'[0.1,0.2,…]'`, cast here.
//
// The reason is that no Go code in this service does arithmetic on an
// embedding. It receives 768 floats from ai-service, hands them to
// Postgres, and never looks at them again. Postgres does the parsing and
// the validation — including rejecting a vector of the wrong width, which
// is the failure that actually matters.
//
// The `::vector` cast is NOT cosmetic. Without it the insert fails
// outright, which is the good outcome; the bad one would be a column loose
// enough to accept the string.
// ─── Ingestion ───────────────────────────────────────────────────────
// Insert or update one authored document, keyed by its identity.
//
// ON CONFLICT against `kd_identity_idx` (title, language, version) is
// what makes ingestion re-runnable: a second run over an unchanged corpus
// updates rows in place rather than doubling the corpus, which would show
// up as retrieval returning the same passage twice and read as a ranking
// bug.
//
// `created_at` is deliberately not touched on update. "When did this
// document first enter the corpus" is a different question from "when was
// it last ingested", and overwriting the first with the second loses it.
func (q *Queries) UpsertKnowledgeDocument(ctx context.Context, arg UpsertKnowledgeDocumentParams) (KnowledgeDocument, error) {
	row := q.db.QueryRow(ctx, upsertKnowledgeDocument,
		arg.Title,
		arg.Category,
		arg.Content,
		arg.Language,
		arg.Source,
		arg.Authority,
		arg.AstrologySystem,
		arg.Metadata,
		arg.SourceChecksum,
	)
	var i KnowledgeDocument
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Language,
		&i.Source,
		&i.Authority,
		&i.AstrologySystem,
		&i.Metadata,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceChecksum,
	)
	return i, err
}
