// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meta.sql

package dbgen

import (
	"context"
)

const getSchemaMeta = `-- name: GetSchemaMeta :one

SELECT id, application, phase, bootstrapped_at, updated_at FROM schema_meta WHERE id = 1
`

// Queries against schema_meta.
//
// Small on purpose: Phase 0 has no domain tables. This exists so the
// sqlc pipeline is wired and proven end to end before Phase 1 needs it,
// rather than being set up under time pressure alongside auth.
func (q *Queries) GetSchemaMeta(ctx context.Context) (SchemaMetum, error) {
	row := q.db.QueryRow(ctx, getSchemaMeta)
	var i SchemaMetum
	err := row.Scan(
		&i.ID,
		&i.Application,
		&i.Phase,
		&i.BootstrappedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSchemaPhase = `-- name: SetSchemaPhase :one
UPDATE schema_meta
SET phase = $1,
    updated_at = now()
WHERE id = 1
RETURNING id, application, phase, bootstrapped_at, updated_at
`

func (q *Queries) SetSchemaPhase(ctx context.Context, phase string) (SchemaMetum, error) {
	row := q.db.QueryRow(ctx, setSchemaPhase, phase)
	var i SchemaMetum
	err := row.Scan(
		&i.ID,
		&i.Application,
		&i.Phase,
		&i.BootstrappedAt,
		&i.UpdatedAt,
	)
	return i, err
}
