// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"
)

type SchemaMetum struct {
	ID             int16
	Application    string
	Phase          string
	BootstrappedAt time.Time
	UpdatedAt      time.Time
}
