// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ─── messages: append ────────────────────────────────────────────────
	// One turn, and the conversation's counter, in a single statement.
	//
	// ── Why the UPDATE is the CTE and the INSERT is the main statement ──
	//
	// The UPDATE is the authorisation. It matches nothing for a non-owner,
	// so `owned` is empty, so the INSERT's SELECT produces no row and no
	// message is written — the same "no row rather than a row the caller is
	// trusted to inspect" shape as the rest of this file, applied to a
	// write. Appending to somebody else's conversation is not merely
	// refused; it is unrepresentable.
	//
	// It is also what keeps `message_count` honest. One statement means the
	// counter and the row land together or not at all: a CHECK violation on
	// the message rolls the increment back with it, and the increment cannot
	// happen without a message because the INSERT is what consumes `owned`.
	//
	// Concurrency: `message_count + 1` is re-evaluated after the row lock
	// the UPDATE takes, so two simultaneous appends serialise and neither
	// increment is lost. No explicit `FOR UPDATE` is needed — that is for
	// read-then-write sequences (balances, Phase 7), not for a counter
	// incremented in terms of itself.
	//
	// ── Why not a trigger ──
	//
	// A trigger on `messages` is the reflex and it is a trap here. An
	// AFTER DELETE trigger decrementing the counter would fire for every
	// message during a conversation's `ON DELETE CASCADE` and try to UPDATE
	// the `conversations` row that is itself being deleted. That either
	// errors or silently does nothing depending on trigger timing, and the
	// failure appears at account deletion — the one path that must not have
	// surprises. The cascade needs no decrement, because the counter is
	// deleted along with the row that holds it.
	// ── Two pieces of sqlc pedantry, both load-bearing ──
	//
	// The predicate columns are table-qualified and the CTE's output column
	// is aliased. Postgres accepts the unqualified, unaliased version
	// without complaint; sqlc's analyser resolves names across the whole
	// statement, sees `id` on both `conversations` and `messages`, and fails
	// the build with `column reference "id" is ambiguous` — reported at a
	// line several statements further down, which is not a hint worth
	// rediscovering.
	AppendMessage(ctx context.Context, arg AppendMessageParams) (AppendMessageRow, error)
	// The whole tree in ONE round trip.
	//
	// 819 rows per chart — 9 mahadashas, 81 antardashas, 729
	// pratyantardashas — inserted one at a time was 819 round trips inside
	// the transaction, and measured as the dominant cost of a cold chart
	// request: 564 ms against a 350 ms budget. COPY makes it one.
	//
	// `id` is supplied by the caller rather than defaulted, because a child
	// row needs its parent's id BEFORE either is written. Generating the
	// UUIDs in Go is what makes a single batch possible at all.
	//
	// Rows must arrive parents-first: the parent_id foreign key is checked
	// per row, so a level-2 row ahead of its level-1 parent is rejected. A
	// breadth-first flatten gives that ordering for free.
	BulkInsertDashas(ctx context.Context, arg []BulkInsertDashasParams) (int64, error)
	CancelUserDeletion(ctx context.Context, id pgtype.UUID) (User, error)
	// ─── Operational checks ──────────────────────────────────────────────
	// The two numbers the phase gate asks for (§16: ≥400 documents, chunked,
	// embedded) plus the one that says whether it is sound.
	//
	// `unembedded` reads through `kc_unembedded_idx`, a partial index on
	// `embedding IS NULL`. In a healthy corpus it is empty, which is the
	// point: an unembedded chunk is invisible to vector search while still
	// matching keyword search, and that half-presence reads as a ranking
	// mystery rather than as missing data.
	CountKnowledgeCorpus(ctx context.Context) (CountKnowledgeCorpusRow, error)
	// How many links this user currently has working, across all profiles.
	// Used to cap the total: an unbounded number of live bearer credentials
	// per account is a liability the owner cannot reason about.
	CountLiveChartShares(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountPlaces(ctx context.Context) (int64, error)
	// Astrology queries. See docs/specs/PHASE-02-ASTROLOGY-ENGINE.md §3.
	//
	// Every read of a birth profile or a chart is scoped by user_id in the
	// SQL itself, not by a check in the handler. A chart is among the most
	// sensitive objects in the system, and a predicate in the query is a
	// guarantee the caller cannot forget to apply.
	// ─── birth profiles ──────────────────────────────────────────────────
	CreateBirthProfile(ctx context.Context, arg CreateBirthProfileParams) (BirthProfile, error)
	// Share-link queries. See docs/specs/PHASE-03-KUNDLI-UI.md task 3.16.
	//
	// Two access paths, and they are deliberately asymmetric:
	//
	//   The OWNER's queries are scoped by user_id in the SQL, like every
	//   other read in this service. A predicate in the query is a guarantee
	//   the handler cannot forget to apply.
	//
	//   The VIEWER's query is scoped by nothing but the token hash, because
	//   a viewer has no account. The token IS the authorisation — which is
	//   why liveness (not expired, not revoked) is in the WHERE clause
	//   rather than checked in Go afterwards. A dead link must return no
	//   row, not a row the caller is trusted to inspect.
	// ─── creating and listing, for the owner ─────────────────────────────
	CreateChartShare(ctx context.Context, arg CreateChartShareParams) (ChartShare, error)
	// Conversation, message and context queries. PHASE-05 task 5.10.
	//
	// ── Every read is scoped by user_id in the SQL ──
	//
	// Not in the handler. `shares.sql` put it this way and it is worth
	// repeating because this file is where it matters most: "a predicate in
	// the query is a guarantee the handler cannot forget to apply."
	//
	// `.claude/rules/security.md`: "Cross-user access returns 404, not 403 —
	// a 403 confirms the resource exists." A query that returned the row and
	// left the ownership decision to Go would make that guarantee depend on
	// every future call site remembering to check — including the ones added
	// by tasks 5.12, 5.16 and 5.17, by someone who has not read this
	// comment. Scoped in the SQL, a non-owner's request produces NO ROW,
	// `pgx.ErrNoRows`, and a 404 that cannot accidentally become a 403.
	//
	// The writes are scoped the same way, which matters more: a rename or an
	// archive that affected somebody else's row would be a silent
	// cross-account mutation, not merely an information leak.
	//
	// ── Why the message queries name their columns ──
	//
	// `messages.search_tsv` is a GENERATED tsvector — index payload, not
	// data. `SELECT *` would carry it over the wire on every message read,
	// into a Go field no code in this service can use (sqlc types tsvector
	// as `interface{}`). The column lists below are therefore explicit and
	// identical, in schema order:
	//
	//   id, conversation_id, role, content, intent, model, provider_id,
	//   prompt_version, input_tokens, output_tokens, latency_ms, is_partial,
	//   safety_flags, is_reported, created_at
	//
	// `conversations` and `message_contexts` have no generated column, so
	// they use `*`.
	// ─── conversations: create ───────────────────────────────────────────
	// Start a thread against one of the caller's own birth profiles.
	//
	// INSERT ... SELECT rather than INSERT ... VALUES, and that is the whole
	// point of this query. `birth_profile_id` arrives from the client, so
	// VALUES would happily open a conversation bound to another user's
	// chart — §12's first checklist item ("chart context comes from the
	// chart Go loaded after an ownership check — never from an ID in the
	// message body") lost at the moment the thread is created rather than
	// when it is read.
	//
	// Selecting the row makes the profile's ownership the precondition for
	// the insert: a foreign profile matches nothing, no row is inserted, and
	// the caller gets `pgx.ErrNoRows` → 404.
	//
	// `user_id` is taken from the profile row, not from the parameter, so
	// the two cannot disagree. The parameter only narrows.
	//
	// `is_active` is required too. Correcting a birth time supersedes the
	// old profile (000003), and a NEW thread started on a superseded
	// version would be read against a chart its owner has already said was
	// wrong. Existing threads keep pointing at it — that is the audit trail
	// — but nothing new attaches to it.
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	// ─── Preferences ─────────────────────────────────────────────────────
	CreateDefaultPreferences(ctx context.Context, userID pgtype.UUID) (UserPreference, error)
	// ─── Sessions ────────────────────────────────────────────────────────
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUserWithEmail(ctx context.Context, email *string) (User, error)
	CreateUserWithPhone(ctx context.Context, phone *string) (User, error)
	DeactivateBirthProfile(ctx context.Context, arg DeactivateBirthProfileParams) (int64, error)
	// Scoped by user. `:execrows` rather than `:exec` so the handler can
	// tell "deleted" from "not yours or not there" and return 404 for both
	// — the two cases must be indistinguishable to the client.
	//
	// The messages and their contexts go with it, by `ON DELETE CASCADE` in
	// migration 000009 rather than by two more statements here. §16 gates on
	// it ("Deleting a conversation cascades to messages and contexts") and
	// the database is the only place that cannot forget.
	DeleteConversation(ctx context.Context, arg DeleteConversationParams) (int64, error)
	// Recomputing replaces the whole tree. Deleting first keeps it a tree
	// rather than two overlapping generations of one.
	DeleteDashasForChart(ctx context.Context, chartID pgtype.UUID) (int64, error)
	// ─── housekeeping ────────────────────────────────────────────────────
	// Swept by the worker.
	//
	// Rows are kept for a grace period after death rather than deleted at
	// the instant they expire, so an owner opening the share screen can
	// still see that a link existed and has lapsed. A row that vanishes at
	// expiry reads as "I never made that link".
	DeleteExpiredChartShares(ctx context.Context, expiresAt time.Time) (int64, error)
	// Housekeeping for the worker. Expired rows prove nothing and grow
	// forever.
	DeleteExpiredSessions(ctx context.Context) error
	// Clear a document's chunks before re-inserting them.
	//
	// Replace rather than upsert, because re-chunking can produce a DIFFERENT
	// NUMBER of chunks. An upsert keyed on (document_id, chunk_index) would
	// leave the tail of the previous run behind — orphan chunks at indexes the
	// new run never reached, still matching keyword search, still being
	// retrieved. They would be the only chunks in the corpus whose text no
	// authored file contains.
	DeleteKnowledgeChunks(ctx context.Context, documentID pgtype.UUID) (int64, error)
	DeleteTransitsBefore(ctx context.Context, timestamp time.Time) (int64, error)
	// Which periods were running at a given instant — one per level, so a
	// caller gets the Maha, Antar and Pratyantar in a single round trip.
	//
	// Half-open interval: start <= t < end. A closed interval would return
	// two rows on the boundary instant, since one period's end is the next
	// one's start.
	FindDashaAt(ctx context.Context, arg FindDashaAtParams) ([]Dasha, error)
	// ─── Identities ──────────────────────────────────────────────────────
	FindIdentity(ctx context.Context, arg FindIdentityParams) (AuthIdentity, error)
	// Used only on the reuse path, to find which family to revoke. Deliberately
	// ignores used_at/revoked_at: the whole point is to locate a token that
	// has already been spent.
	FindSessionByHash(ctx context.Context, refreshHash []byte) (Session, error)
	// Auth queries. See docs/specs/PHASE-01-AUTH-AND-USERS.md §3.
	FindUserByEmail(ctx context.Context, email *string) (User, error)
	FindUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	FindUserByPhone(ctx context.Context, phone *string) (User, error)
	// The same window, grouped. p50 and p95 latency come from
	// percentile_disc rather than an average: an average latency hides the
	// tail, and the tail is what users notice.
	GetAIUsageByJob(ctx context.Context, arg GetAIUsageByJobParams) ([]GetAIUsageByJobRow, error)
	// Totals over a window, for the admin usage view.
	//
	// COALESCE on every aggregate: SUM over zero rows is NULL, and a
	// dashboard rendering "null requests, null cost" for a quiet hour is
	// indistinguishable from a broken query.
	//
	// `cost_micros` is summed as BIGINT and returned as BIGINT. No cast to
	// NUMERIC anywhere — invariant 4, and a NUMERIC that reaches Go through
	// a float is exactly the bug the rule exists to prevent.
	GetAIUsageSummary(ctx context.Context, arg GetAIUsageSummaryParams) (GetAIUsageSummaryRow, error)
	// Scoped by user. A caller asking for someone else's profile gets no
	// row, which the handler turns into a 404 — never a 403, because a 403
	// confirms the row exists.
	GetBirthProfile(ctx context.Context, arg GetBirthProfileParams) (BirthProfile, error)
	// Joined to birth_profiles so ownership is enforced in the same
	// statement that fetches the data. A separate ownership check is a
	// check someone can forget.
	GetChart(ctx context.Context, arg GetChartParams) (Chart, error)
	// ─── conversations: read ─────────────────────────────────────────────
	// One thread, for its owner.
	//
	// Archived threads are included: §7's history screen can open one, and
	// "archived" means "not in the default list", not "gone".
	GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error)
	// What the database already holds for this identity.
	//
	// Returns the checksum and the chunk count together because both have to
	// match before a re-run can skip a document. A matching checksum with
	// zero chunks is a previous run that failed between the document insert
	// and the chunk inserts — and skipping that leaves a document in the
	// corpus with nothing retrievable in it.
	GetKnowledgeDocumentChecksum(ctx context.Context, arg GetKnowledgeDocumentChecksumParams) (GetKnowledgeDocumentChecksumRow, error)
	// The "Why am I seeing this?" payload (§7), and §16's "renders the real
	// stored context".
	//
	// A read, not a regeneration. Rebuilding the context from the chart
	// would use today's context builder against today's corpus and answer a
	// different question — "what would we retrieve now?" — while looking
	// like it answered the original one. Task 5.5's dimension migration
	// re-embeds the whole corpus, and re-chunking changes which chunk ids
	// exist at all, so the regenerated answer would drift without anything
	// appearing to change.
	//
	// Two joins to reach `user_id`: contexts hang off messages, which hang
	// off conversations, which is where ownership lives. The alternative —
	// trusting the handler to have loaded the conversation first — is the
	// thing this file refuses to do.
	GetMessageContext(ctx context.Context, arg GetMessageContextParams) (MessageContext, error)
	GetPlace(ctx context.Context, id int32) (Place, error)
	GetPreferences(ctx context.Context, userID pgtype.UUID) (UserPreference, error)
	GetSadeSatiWindow(ctx context.Context, moonSignIndex int16) (SadeSatiWindow, error)
	// Queries against schema_meta.
	//
	// Small on purpose: Phase 0 has no domain tables. This exists so the
	// sqlc pipeline is wired and proven end to end before Phase 1 needs it,
	// rather than being set up under time pressure alongside auth.
	GetSchemaMeta(ctx context.Context) (SchemaMetum, error)
	// Real deletion, not a flag. Every user-owned table declares ON DELETE
	// CASCADE, so this removes the lot — which is what the Phase 1 gate
	// means by "no row anywhere references the user".
	//
	// audit_logs is the deliberate exception: its user_id is not a foreign
	// key, so the record that a deletion happened survives the deletion. It
	// holds IDs and enums only, never PII.
	HardDeleteUser(ctx context.Context, id pgtype.UUID) error
	// Every model call, written by Go from the telemetry Python returned.
	// See docs/specs/PHASE-04-AI-INFRASTRUCTURE.md §8.
	//
	// No query here selects message content, because no column holds any.
	// Called inside the same transaction as the message write (Phase 5), so
	// a request that cost money cannot be missing from the bill because a
	// separate logging call failed.
	InsertAIRequestLog(ctx context.Context, arg InsertAIRequestLogParams) (AiRequestLog, error)
	// ─── dashas ──────────────────────────────────────────────────────────
	InsertDasha(ctx context.Context, arg InsertDashaParams) (Dasha, error)
	// One chunk, with its vector.
	//
	// See the note at the top of this file for why the vector is a string
	// here and cast in the SQL.
	InsertKnowledgeChunk(ctx context.Context, arg InsertKnowledgeChunkParams) error
	// ─── message_contexts ────────────────────────────────────────────────
	// What was supplied to the model for one assistant message.
	//
	// `prompt_version` is NOT a parameter. It is selected off the message
	// row, so the copy here and the copy on `messages` cannot disagree —
	// the duplication §5 implies becomes a derivation. A message with no
	// `prompt_version` fails the NOT NULL and the insert errors loudly,
	// which is correct: a context row for a response that does not record
	// which prompt produced it cannot explain that response.
	//
	// INSERT ... SELECT also makes a context for a non-existent message
	// return no row rather than a foreign-key error, matching the shape of
	// every other write in this file.
	//
	// Not scoped by user, and that is deliberate — this runs inside the
	// chat pipeline, immediately after `AppendMessage` returned the message
	// it is about, in the same request. There is no client-supplied id to
	// validate. The scoping lives on the READ, below, which is where a
	// client-supplied id does arrive.
	InsertMessageContext(ctx context.Context, arg InsertMessageContextParams) (MessageContext, error)
	// ON CONFLICT DO UPDATE rather than DO NOTHING: DO NOTHING returns no
	// row, so the caller cannot tell "already linked" from "insert failed"
	// without a second query.
	LinkIdentity(ctx context.Context, arg LinkIdentityParams) (AuthIdentity, error)
	// Newest first, served by ai_logs_user_idx.
	ListAIRequestLogsForUser(ctx context.Context, arg ListAIRequestLogsForUserParams) ([]AiRequestLog, error)
	// Every AI request this person made, for their data export.
	//
	// PHASE-04 §8 keeps message CONTENT out of this table entirely, so what
	// a person receives here is the shape of their usage and nothing they
	// wrote: when, which job, which intent, what it cost. That is still
	// personal data — "asked about medical matters on these dates" is a
	// fact about a person — which is why it is exported rather than filed
	// as telemetry.
	//
	// `cost_micros` is included deliberately. Phase 7 bills from this
	// table, and an export that hides the number a charge is computed from
	// would be the one field a person most reasonably wants to check.
	ListAIRequestsForUser(ctx context.Context, userID pgtype.UUID) ([]ListAIRequestsForUserRow, error)
	// The admin incident feed. Served by the PARTIAL index, so this stays
	// fast as the table grows — failures are a small fraction of rows and a
	// full index on the boolean would be scanned rather than used.
	ListAISafetyIncidents(ctx context.Context, arg ListAISafetyIncidentsParams) ([]AiRequestLog, error)
	ListActiveBirthProfiles(ctx context.Context, userID pgtype.UUID) ([]BirthProfile, error)
	// One row per DEVICE, not per session.
	//
	// A device is a family: every refresh issues a new session row sharing
	// the family_id of the token it replaced, so a single browser open for an
	// hour accumulates a dozen rows. Listing those as "devices" is both
	// wrong and alarming — the user sees twelve unknown sign-ins — and
	// revoking one of them kills a spent link in the chain rather than the
	// device.
	//
	// DISTINCT ON takes the newest row per family, which carries the most
	// recent user agent and expiry.
	ListActiveDevices(ctx context.Context, userID pgtype.UUID) ([]Session, error)
	// Every row, including superseded links in a rotation chain. Used by the
	// data export, where completeness is the point.
	ListActiveSessions(ctx context.Context, userID pgtype.UUID) ([]Session, error)
	// Every version, active and superseded, for the data export.
	//
	// ListActiveBirthProfiles deliberately hides superseded rows because the
	// product only ever shows the current one. An export is the opposite
	// case: the history is what explains a reading given before a correction,
	// and dropping it hands back less than was actually stored.
	ListAllBirthProfilesForUser(ctx context.Context, userID pgtype.UUID) ([]BirthProfile, error)
	// Every thread, archived or not, uncapped — for the data export.
	//
	// Uncapped on purpose, like `ListChartSharesForUser`. A portability
	// export that silently drops the tail is the failure
	// `internal/users/export.go` exists to prevent: the user reads an absent
	// row as "I never had that conversation".
	ListAllConversationsForUser(ctx context.Context, userID pgtype.UUID) ([]Conversation, error)
	// The archive, as its own list rather than a flag on the one above.
	ListArchivedConversations(ctx context.Context, arg ListArchivedConversationsParams) ([]Conversation, error)
	ListAuditLogsForUser(ctx context.Context, arg ListAuditLogsForUserParams) ([]AuditLog, error)
	// The history behind one profile, newest first.
	//
	// Walks superseded_by BACKWARDS from the given id: each step finds the
	// version that this one replaced. Callers ask for the history of the
	// profile they are looking at, which is the active one, which is the
	// newest — so walking back reaches every earlier version.
	//
	// Every column reference is qualified. An unqualified `id` here is
	// ambiguous between the CTE and the table, and sqlc rejects it, which is
	// the right moment to find out rather than at runtime.
	ListBirthProfileVersions(ctx context.Context, arg ListBirthProfileVersionsParams) ([]ListBirthProfileVersionsRow, error)
	// Every link this user has created for one profile, newest first.
	// Revoked and expired rows are included on purpose: "which links did I
	// make, and which are dead" is the question this answers.
	ListChartShares(ctx context.Context, arg ListChartSharesParams) ([]ChartShare, error)
	// Every link this user has created, across all their profiles.
	//
	// For the data export: "who can currently see my chart" is a question
	// only this answers, and an export omitting it hands somebody a copy of
	// their data with the sharing removed.
	ListChartSharesForUser(ctx context.Context, userID pgtype.UUID) ([]ChartShare, error)
	// Finds charts built by an older engine, so a library upgrade can be
	// followed by a targeted recompute instead of a guess.
	ListChartsByEngineVersion(ctx context.Context, arg ListChartsByEngineVersionParams) ([]Chart, error)
	ListChartsForProfile(ctx context.Context, arg ListChartsForProfileParams) ([]Chart, error)
	// The history screen's default list: this user's live threads, most
	// recently active first.
	//
	// `is_archived = FALSE` is spelled out rather than parameterised. A
	// single query with `is_archived = $2` would read as tidier and would
	// defeat `conversations_user_active_idx`, which is partial precisely
	// because this is the query that runs on every history load.
	ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error)
	ListDashasByLevel(ctx context.Context, arg ListDashasByLevelParams) ([]Dasha, error)
	// Needed by the data export. Without it the export declares an
	// auth_identities field and always returns [], which is worse than
	// omitting it: it tells the user there are none.
	ListIdentitiesForUser(ctx context.Context, userID pgtype.UUID) ([]AuthIdentity, error)
	// Every stored document's identity and checksum, for verifying the corpus
	// against what is on disk.
	ListKnowledgeChecksums(ctx context.Context) ([]ListKnowledgeChecksumsRow, error)
	// ─── messages: read ──────────────────────────────────────────────────
	// One conversation's turns, oldest first, for its owner.
	//
	// The join is the ownership check. `conversation_id` alone would return
	// the whole of somebody else's thread to anyone who learned its id,
	// which is the single worst read in this product: it is the complete
	// text of what a person asked about their health and their marriage.
	//
	// `id` is the tiebreaker on `created_at`. `now()` is the transaction's
	// start time, so two messages written in one transaction share a
	// timestamp exactly; a random UUID is not a meaningful order but it is a
	// STABLE one, which is what keeps a paginated list from repeating or
	// skipping a row. In normal operation the user's turn and the
	// assistant's are seconds apart (§6 persists the user message before the
	// model is called), so the tiebreaker is a guard, not the usual path.
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error)
	// Every message this person has, across every conversation — the data
	// export.
	//
	// Capped, unlike the conversation list, and the asymmetry is deliberate:
	// a long-lived account has tens of thousands of messages and a response
	// that times out is not an export. The audit log is capped for the same
	// reason in `internal/users/export.go`. Ordered oldest-first so a
	// truncated export is a truncated BEGINNING of the history rather than
	// an arbitrary slice.
	ListMessagesForUser(ctx context.Context, arg ListMessagesForUserParams) ([]ListMessagesForUserRow, error)
	// The last N turns, for §5's context window (`CHAT_RECENT_MESSAGE_WINDOW`).
	//
	// Newest first, because "the last 6" has to be taken from the recent end
	// — the caller reverses them before building the prompt. Ordering
	// ascending with a LIMIT would return the OLDEST six, which is the
	// version of this query that looks right and produces a model with no
	// idea what was just said.
	//
	// Partial messages are included. A disconnect mid-answer is part of the
	// thread the user can see, and omitting it from the context would make
	// the model's next turn contradict the screen.
	ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]ListRecentMessagesRow, error)
	// For the health probe and for anyone reading the table by hand.
	ListSadeSatiWindows(ctx context.Context) ([]SadeSatiWindow, error)
	// Global and free of personal data, so no user scoping — and that is
	// what makes them safe to cache across all users.
	ListTransitsAt(ctx context.Context, arg ListTransitsAtParams) ([]Transit, error)
	ListUsersPastDeletionGrace(ctx context.Context, deletionRequestedAt pgtype.Timestamptz) ([]User, error)
	// §7's Report button (task 5.17).
	//
	// Scoped by owner through the conversation, so a user can only report an
	// answer given to them. Without the join, any message id would be
	// reportable by anyone — a way to flood the review queue with other
	// people's conversations.
	//
	// Idempotent: reporting twice sets a boolean that is already true.
	// `:execrows` returns 0 for a message that is not this user's, which the
	// handler turns into 404.
	MarkMessageReported(ctx context.Context, arg MarkMessageReportedParams) (int64, error)
	// ─── conversations: update and delete ────────────────────────────────
	// Scoped by user, so renaming somebody else's thread affects no row and
	// the handler answers 404 — never 403, which would confirm it exists.
	//
	// `updated_at` is deliberately NOT touched. It is the history sort key
	// and it means "when did this conversation last have something said in
	// it"; a rename would otherwise shuffle a year-old thread to the top of
	// the list for a cosmetic edit.
	RenameConversation(ctx context.Context, arg RenameConversationParams) (Conversation, error)
	// ─── Deletion ────────────────────────────────────────────────────────
	RequestUserDeletion(ctx context.Context, id pgtype.UUID) (User, error)
	// ─── resolving, for the viewer ───────────────────────────────────────
	// The whole viewer authorisation, in one predicate.
	//
	// Liveness is in the WHERE clause rather than checked in Go afterwards,
	// so an expired or revoked link returns NO ROW. A query that returned
	// the row and left the decision to the caller would make the guarantee
	// depend on every future call site remembering to check.
	//
	// NOW() is the database's clock, not the API's. Several replicas with
	// slightly different clocks would otherwise disagree about whether a
	// link is still live, and an expiry that depends on which instance you
	// reach is not an expiry.
	ResolveChartShare(ctx context.Context, tokenHash string) (ChartShare, error)
	RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error
	// ─── revoking ────────────────────────────────────────────────────────
	// Scoped by user, so revoking somebody else's link affects no row and
	// the handler answers 404 — never 403, which would confirm it exists.
	//
	// Idempotent: revoking an already-revoked link keeps the ORIGINAL
	// timestamp, because "when did I turn this off" must not be rewritten by
	// a second click.
	RevokeChartShare(ctx context.Context, arg RevokeChartShareParams) (ChartShare, error)
	// Every live link for one profile, killed at once.
	//
	// Called when birth details are corrected. A correction creates a new
	// profile version, and a link pointing at the old one would keep serving
	// a chart its owner has already decided was wrong.
	RevokeChartSharesForProfile(ctx context.Context, arg RevokeChartSharesForProfileParams) error
	// Signs one device out by ending its whole lineage.
	//
	// Scoped by user_id, so a caller cannot revoke another account's device
	// even with a valid family id — the row count is what lets the handler
	// answer 404 rather than a misleading 204.
	RevokeDeviceFamily(ctx context.Context, arg RevokeDeviceFamilyParams) (int64, error)
	// :execrows, not :exec. An :exec cannot distinguish "revoked it" from
	// "matched nothing", so revoking someone else's session — which the
	// user_id predicate correctly refuses — returned 204 and told the caller
	// it had worked. The row count is what lets the handler answer 404.
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error)
	// One leaked token invalidates every descendant of it. Cheap to run and
	// it turns a silent compromise into a forced re-authentication.
	RevokeTokenFamily(ctx context.Context, familyID pgtype.UUID) error
	// The single most important statement in this phase.
	//
	// Check and update in ONE statement. Two concurrent refreshes presenting
	// the same token: Postgres serialises the UPDATE, so exactly one matches
	// `used_at IS NULL` and gets a row back. The other gets no rows, which
	// the caller treats as reuse and revokes the family.
	//
	// A read-then-write in Go would let both pass the check before either
	// wrote — the classic TOCTOU that makes a leaked token usable twice. No
	// application lock is needed, and a mocked database cannot test this.
	RotateRefreshToken(ctx context.Context, refreshHash []byte) (Session, error)
	// Full-text search across one user's own history (§7, task 5.16).
	//
	// Scoped by `c.user_id` in the same WHERE clause as the match, so a
	// search can only ever rank this person's own text. A search endpoint is
	// the easiest place in a product to leak the whole corpus of user
	// content, because the predicate that limits it looks like a filter
	// rather than like authorisation.
	//
	// `websearch_to_tsquery` rather than `plainto_tsquery`: it accepts what
	// people actually type into a search box — quoted phrases, `or`, a
	// leading `-` to exclude — and, unlike `to_tsquery`, it cannot raise a
	// syntax error on user input. A search that 500s on an apostrophe is a
	// search nobody uses twice.
	//
	// The query text is matched against `search_tsv`, the generated column,
	// so `messages_search_idx` serves it. `ts_rank` recomputes over the
	// matched rows only, which is a user-sized set, not a corpus-sized one.
	//
	// `conversation_title` comes along because a search hit is useless
	// without the thread it belongs to — the UI needs somewhere to send the
	// tap.
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error)
	// ─── places ──────────────────────────────────────────────────────────
	// Prefix match, ranked by population — which is what makes "jaip"
	// return Jaipur, Rajasthan rather than a village of 600 people. The
	// ranking matters more than the matching at the highest drop-off point
	// in the product.
	SearchPlaces(ctx context.Context, arg SearchPlacesParams) ([]Place, error)
	// Archive or restore. One query for both directions, because a toggle
	// implemented as two endpoints drifts.
	//
	// `updated_at` untouched, same reasoning as the rename.
	SetConversationArchived(ctx context.Context, arg SetConversationArchivedParams) (Conversation, error)
	SetSchemaPhase(ctx context.Context, phase string) (SchemaMetum, error)
	// Marks a version replaced. Returns the row so the caller can tell
	// "superseded it" from "there was nothing to supersede" without a second
	// query — the same reason RevokeSession became :execrows in Phase 1.
	SupersedeBirthProfile(ctx context.Context, arg SupersedeBirthProfileParams) (BirthProfile, error)
	// Records that a live link was opened.
	//
	// A count and a timestamp, never who. A log of viewers would be a record
	// of one person's interest in another, which this product has no
	// business keeping — and which nobody consented to when they opened a
	// link someone sent them.
	TouchChartShare(ctx context.Context, id pgtype.UUID) error
	TouchLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (UserPreference, error)
	// COALESCE so a PATCH omitting a field leaves it alone rather than
	// nulling it. Only name and gender are writable here; email and phone
	// change through a verification flow, never a profile edit.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// ─── charts ──────────────────────────────────────────────────────────
	// Keyed on every input that affects the output. Recomputing with the
	// same inputs replaces the data in place; changing the ayanamsa creates
	// a different row rather than overwriting an unrelated chart.
	UpsertChart(ctx context.Context, arg UpsertChartParams) (Chart, error)
	// Knowledge-base queries. PHASE-05 tasks 5.1 and 5.4.
	//
	// Written by `cmd/ingest-kb` only. `ai-service` reads these tables as
	// `astro_ro` through asyncpg (task 5.6) rather than through here — the
	// single-writer rule means Go owns the writes, not that Go owns every
	// read.
	//
	// ── Why the embedding is a string in Go ──
	//
	// Left to itself, sqlc maps `vector(768)` to `*pgvector.Vector` and pulls
	// in github.com/pgvector/pgvector-go — a new direct dependency that also
	// has to be registered with every pgx pool before the type encodes. It is
	// overridden to `string` in sqlc.yaml, and the vector travels as
	// pgvector's own documented text form, `'[0.1,0.2,…]'`, cast here.
	//
	// The reason is that no Go code in this service does arithmetic on an
	// embedding. It receives 768 floats from ai-service, hands them to
	// Postgres, and never looks at them again. Postgres does the parsing and
	// the validation — including rejecting a vector of the wrong width, which
	// is the failure that actually matters.
	//
	// The `::vector` cast is NOT cosmetic. Without it the insert fails
	// outright, which is the good outcome; the bad one would be a column loose
	// enough to accept the string.
	// ─── Ingestion ───────────────────────────────────────────────────────
	// Insert or update one authored document, keyed by its identity.
	//
	// ON CONFLICT against `kd_identity_idx` (title, language, version) is
	// what makes ingestion re-runnable: a second run over an unchanged corpus
	// updates rows in place rather than doubling the corpus, which would show
	// up as retrieval returning the same passage twice and read as a ranking
	// bug.
	//
	// `created_at` is deliberately not touched on update. "When did this
	// document first enter the corpus" is a different question from "when was
	// it last ingested", and overwriting the first with the second loses it.
	UpsertKnowledgeDocument(ctx context.Context, arg UpsertKnowledgeDocumentParams) (KnowledgeDocument, error)
	// Keyed on the GeoNames id, so re-running the importer updates rows
	// instead of duplicating them.
	UpsertPlace(ctx context.Context, arg UpsertPlaceParams) error
	// Sade Sati windows. See docs/specs/PHASE-03-KUNDLI-UI.md §15.
	//
	// Twelve rows, one per natal Moon sign, refreshed by the worker. Read on
	// the request path by primary key, so the answer survives astro-service
	// being unreachable.
	// Idempotent on the sign, so a retried refresh — or two replicas that
	// both got through — rewrites the row rather than failing or doubling
	// it. The same reasoning as UpsertTransit.
	UpsertSadeSatiWindow(ctx context.Context, arg UpsertSadeSatiWindowParams) (SadeSatiWindow, error)
	// ─── transits ────────────────────────────────────────────────────────
	UpsertTransit(ctx context.Context, arg UpsertTransitParams) (Transit, error)
	// ─── Audit ───────────────────────────────────────────────────────────
	WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) error
}

var _ Querier = (*Queries)(nil)
