// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sadesati.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSadeSatiWindow = `-- name: GetSadeSatiWindow :one
SELECT moon_sign_index, moon_sign, started_at, ends_at, computed_for, computed_at FROM sade_sati_windows WHERE moon_sign_index = $1
`

func (q *Queries) GetSadeSatiWindow(ctx context.Context, moonSignIndex int16) (SadeSatiWindow, error) {
	row := q.db.QueryRow(ctx, getSadeSatiWindow, moonSignIndex)
	var i SadeSatiWindow
	err := row.Scan(
		&i.MoonSignIndex,
		&i.MoonSign,
		&i.StartedAt,
		&i.EndsAt,
		&i.ComputedFor,
		&i.ComputedAt,
	)
	return i, err
}

const listSadeSatiWindows = `-- name: ListSadeSatiWindows :many
SELECT moon_sign_index, moon_sign, started_at, ends_at, computed_for, computed_at FROM sade_sati_windows ORDER BY moon_sign_index
`

// For the health probe and for anyone reading the table by hand.
func (q *Queries) ListSadeSatiWindows(ctx context.Context) ([]SadeSatiWindow, error) {
	rows, err := q.db.Query(ctx, listSadeSatiWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SadeSatiWindow{}
	for rows.Next() {
		var i SadeSatiWindow
		if err := rows.Scan(
			&i.MoonSignIndex,
			&i.MoonSign,
			&i.StartedAt,
			&i.EndsAt,
			&i.ComputedFor,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSadeSatiWindow = `-- name: UpsertSadeSatiWindow :one

INSERT INTO sade_sati_windows (
    moon_sign_index, moon_sign, started_at, ends_at, computed_for
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (moon_sign_index) DO UPDATE SET
    moon_sign    = EXCLUDED.moon_sign,
    started_at   = EXCLUDED.started_at,
    ends_at      = EXCLUDED.ends_at,
    computed_for = EXCLUDED.computed_for,
    computed_at  = NOW()
RETURNING moon_sign_index, moon_sign, started_at, ends_at, computed_for, computed_at
`

type UpsertSadeSatiWindowParams struct {
	MoonSignIndex int16
	MoonSign      string
	StartedAt     pgtype.Timestamptz
	EndsAt        pgtype.Timestamptz
	ComputedFor   time.Time
}

// Sade Sati windows. See docs/specs/PHASE-03-KUNDLI-UI.md §15.
//
// Twelve rows, one per natal Moon sign, refreshed by the worker. Read on
// the request path by primary key, so the answer survives astro-service
// being unreachable.
// Idempotent on the sign, so a retried refresh — or two replicas that
// both got through — rewrites the row rather than failing or doubling
// it. The same reasoning as UpsertTransit.
func (q *Queries) UpsertSadeSatiWindow(ctx context.Context, arg UpsertSadeSatiWindowParams) (SadeSatiWindow, error) {
	row := q.db.QueryRow(ctx, upsertSadeSatiWindow,
		arg.MoonSignIndex,
		arg.MoonSign,
		arg.StartedAt,
		arg.EndsAt,
		arg.ComputedFor,
	)
	var i SadeSatiWindow
	err := row.Scan(
		&i.MoonSignIndex,
		&i.MoonSign,
		&i.StartedAt,
		&i.EndsAt,
		&i.ComputedFor,
		&i.ComputedAt,
	)
	return i, err
}
