// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLiveChartShares = `-- name: CountLiveChartShares :one
SELECT COUNT(*) FROM chart_shares
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

// How many links this user currently has working, across all profiles.
// Used to cap the total: an unbounded number of live bearer credentials
// per account is a liability the owner cannot reason about.
func (q *Queries) CountLiveChartShares(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveChartShares, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChartShare = `-- name: CreateChartShare :one


INSERT INTO chart_shares (
    user_id, birth_profile_id, token_hash, scope, expires_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, birth_profile_id, token_hash, scope, expires_at, revoked_at, view_count, last_viewed_at, created_at
`

type CreateChartShareParams struct {
	UserID         pgtype.UUID
	BirthProfileID pgtype.UUID
	TokenHash      string
	Scope          string
	ExpiresAt      time.Time
}

// Share-link queries. See docs/specs/PHASE-03-KUNDLI-UI.md task 3.16.
//
// Two access paths, and they are deliberately asymmetric:
//
//	The OWNER's queries are scoped by user_id in the SQL, like every
//	other read in this service. A predicate in the query is a guarantee
//	the handler cannot forget to apply.
//
//	The VIEWER's query is scoped by nothing but the token hash, because
//	a viewer has no account. The token IS the authorisation — which is
//	why liveness (not expired, not revoked) is in the WHERE clause
//	rather than checked in Go afterwards. A dead link must return no
//	row, not a row the caller is trusted to inspect.
//
// ─── creating and listing, for the owner ─────────────────────────────
func (q *Queries) CreateChartShare(ctx context.Context, arg CreateChartShareParams) (ChartShare, error) {
	row := q.db.QueryRow(ctx, createChartShare,
		arg.UserID,
		arg.BirthProfileID,
		arg.TokenHash,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i ChartShare
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthProfileID,
		&i.TokenHash,
		&i.Scope,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ViewCount,
		&i.LastViewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredChartShares = `-- name: DeleteExpiredChartShares :execrows

DELETE FROM chart_shares
WHERE expires_at < $1
   OR (revoked_at IS NOT NULL AND revoked_at < $1)
`

// ─── housekeeping ────────────────────────────────────────────────────
// Swept by the worker.
//
// Rows are kept for a grace period after death rather than deleted at
// the instant they expire, so an owner opening the share screen can
// still see that a link existed and has lapsed. A row that vanishes at
// expiry reads as "I never made that link".
func (q *Queries) DeleteExpiredChartShares(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredChartShares, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listChartShares = `-- name: ListChartShares :many
SELECT id, user_id, birth_profile_id, token_hash, scope, expires_at, revoked_at, view_count, last_viewed_at, created_at FROM chart_shares
WHERE user_id = $1 AND birth_profile_id = $2
ORDER BY created_at DESC
`

type ListChartSharesParams struct {
	UserID         pgtype.UUID
	BirthProfileID pgtype.UUID
}

// Every link this user has created for one profile, newest first.
// Revoked and expired rows are included on purpose: "which links did I
// make, and which are dead" is the question this answers.
func (q *Queries) ListChartShares(ctx context.Context, arg ListChartSharesParams) ([]ChartShare, error) {
	rows, err := q.db.Query(ctx, listChartShares, arg.UserID, arg.BirthProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChartShare{}
	for rows.Next() {
		var i ChartShare
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BirthProfileID,
			&i.TokenHash,
			&i.Scope,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ViewCount,
			&i.LastViewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChartSharesForUser = `-- name: ListChartSharesForUser :many
SELECT id, user_id, birth_profile_id, token_hash, scope, expires_at, revoked_at, view_count, last_viewed_at, created_at FROM chart_shares
WHERE user_id = $1
ORDER BY created_at DESC
`

// Every link this user has created, across all their profiles.
//
// For the data export: "who can currently see my chart" is a question
// only this answers, and an export omitting it hands somebody a copy of
// their data with the sharing removed.
func (q *Queries) ListChartSharesForUser(ctx context.Context, userID pgtype.UUID) ([]ChartShare, error) {
	rows, err := q.db.Query(ctx, listChartSharesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChartShare{}
	for rows.Next() {
		var i ChartShare
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BirthProfileID,
			&i.TokenHash,
			&i.Scope,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ViewCount,
			&i.LastViewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveChartShare = `-- name: ResolveChartShare :one

SELECT id, user_id, birth_profile_id, token_hash, scope, expires_at, revoked_at, view_count, last_viewed_at, created_at FROM chart_shares
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

// ─── resolving, for the viewer ───────────────────────────────────────
// The whole viewer authorisation, in one predicate.
//
// Liveness is in the WHERE clause rather than checked in Go afterwards,
// so an expired or revoked link returns NO ROW. A query that returned
// the row and left the decision to the caller would make the guarantee
// depend on every future call site remembering to check.
//
// NOW() is the database's clock, not the API's. Several replicas with
// slightly different clocks would otherwise disagree about whether a
// link is still live, and an expiry that depends on which instance you
// reach is not an expiry.
func (q *Queries) ResolveChartShare(ctx context.Context, tokenHash string) (ChartShare, error) {
	row := q.db.QueryRow(ctx, resolveChartShare, tokenHash)
	var i ChartShare
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthProfileID,
		&i.TokenHash,
		&i.Scope,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ViewCount,
		&i.LastViewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeChartShare = `-- name: RevokeChartShare :one

UPDATE chart_shares
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, birth_profile_id, token_hash, scope, expires_at, revoked_at, view_count, last_viewed_at, created_at
`

type RevokeChartShareParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// ─── revoking ────────────────────────────────────────────────────────
// Scoped by user, so revoking somebody else's link affects no row and
// the handler answers 404 — never 403, which would confirm it exists.
//
// Idempotent: revoking an already-revoked link keeps the ORIGINAL
// timestamp, because "when did I turn this off" must not be rewritten by
// a second click.
func (q *Queries) RevokeChartShare(ctx context.Context, arg RevokeChartShareParams) (ChartShare, error) {
	row := q.db.QueryRow(ctx, revokeChartShare, arg.ID, arg.UserID)
	var i ChartShare
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthProfileID,
		&i.TokenHash,
		&i.Scope,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ViewCount,
		&i.LastViewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeChartSharesForProfile = `-- name: RevokeChartSharesForProfile :exec
UPDATE chart_shares
SET revoked_at = NOW()
WHERE birth_profile_id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeChartSharesForProfileParams struct {
	BirthProfileID pgtype.UUID
	UserID         pgtype.UUID
}

// Every live link for one profile, killed at once.
//
// Called when birth details are corrected. A correction creates a new
// profile version, and a link pointing at the old one would keep serving
// a chart its owner has already decided was wrong.
func (q *Queries) RevokeChartSharesForProfile(ctx context.Context, arg RevokeChartSharesForProfileParams) error {
	_, err := q.db.Exec(ctx, revokeChartSharesForProfile, arg.BirthProfileID, arg.UserID)
	return err
}

const touchChartShare = `-- name: TouchChartShare :exec
UPDATE chart_shares
SET view_count = view_count + 1, last_viewed_at = NOW()
WHERE id = $1
`

// Records that a live link was opened.
//
// A count and a timestamp, never who. A log of viewers would be a record
// of one person's interest in another, which this product has no
// business keeping — and which nobody consented to when they opened a
// link someone sent them.
func (q *Queries) TouchChartShare(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchChartShare, id)
	return err
}
