//go:build integration

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"

	"github.com/Vatsalya001/ai-astrology/services/api/internal/knowledge"
	"github.com/Vatsalya001/ai-astrology/services/api/internal/platform/testsupport"
)

/*
PHASE-05 task 5.4 against real Postgres.

`ingest_test.go` already covers the pipeline's logic with a fake store, and
deliberately: it is fast, runs in CI, and tests the branches. This file
tests the things a fake cannot reproduce, which are exactly the ones that
matter here:

  - the `::vector` cast actually accepting `FormatVector`'s output, and
    REJECTING a vector of the wrong width
  - `ON CONFLICT (title, language, version)` matching the real index
  - a real transaction rolling back a real partial write
  - the generated-column `tsv` populating itself from inserted content
  - `astro_ro` being able to read what the writer wrote, which is the whole
    point of the grants in migration 000007

`.claude/rules/testing.md`: "Do not mock the database. The bugs that matter
live in behaviour a mock cannot reproduce."

No model is called. The embedder here is deterministic and local, because
CI must never call a language model — but the DATABASE is real, because the
database is what this file is about.
*/

const embeddingWidth = 768

func TestTheFullPipelineWritesAnEmbeddedCorpus(t *testing.T) {
	ctx := context.Background()
	store, pool, readerDSN, terminate := startStore(ctx, t)
	defer terminate()

	corpus := loadTestCorpus(t)
	embedder := &fixedEmbedder{model: "nomic-embed-text"}

	report, err := knowledge.Ingest(ctx, corpus, embedder, store,
		knowledge.IngestOptions{BatchSize: 4})
	if err != nil {
		t.Fatalf("ingest: %v", err)
	}
	if report.Ingested != len(corpus) {
		t.Fatalf("ingested %d of %d", report.Ingested, len(corpus))
	}

	counts, err := store.Counts(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if int(counts.Documents) != len(corpus) {
		t.Errorf("stored %d documents, chunked %d", counts.Documents, len(corpus))
	}
	if counts.Chunks == 0 {
		t.Fatal("no chunks were stored")
	}

	// The one that would be invisible from the application side. An
	// unembedded chunk still matches keyword search, so retrieval keeps
	// working and quietly loses half its ranking signal.
	if counts.Unembedded != 0 {
		t.Errorf("%d chunks have no embedding", counts.Unembedded)
	}
	if counts.EmbeddingModels != 1 {
		t.Errorf("the corpus holds vectors from %d models", counts.EmbeddingModels)
	}

	// The vector came back as a vector, at the right width, and with the
	// values that went in. `vector_dims` is pgvector's own function, so
	// this is Postgres confirming it parsed the text form rather than
	// storing a string that happened to be accepted.
	var dims int
	var first float32
	err = pool.QueryRow(ctx, `
		SELECT vector_dims(embedding), (embedding::real[])[1]
		FROM knowledge_chunks WHERE embedding IS NOT NULL LIMIT 1`).Scan(&dims, &first)
	if err != nil {
		t.Fatalf("read back a vector: %v", err)
	}
	if dims != embeddingWidth {
		t.Errorf("stored vector has %d dimensions, want %d", dims, embeddingWidth)
	}
	if first != 0.5 {
		t.Errorf("first component round-tripped as %v, want 0.5", first)
	}

	// The generated column. A trigger is the alternative and a trigger is
	// a thing to forget; this asserts the column is actually generated by
	// never having written it.
	var ranked int
	err = pool.QueryRow(ctx, `
		SELECT count(*) FROM knowledge_chunks
		WHERE tsv @@ plainto_tsquery('english', 'saturn')`).Scan(&ranked)
	if err != nil {
		t.Fatalf("keyword search: %v", err)
	}
	if ranked == 0 {
		t.Error("tsv matched nothing for 'saturn'; the generated column is not populating")
	}

	// `astro_ro` reading what the writer wrote. Migration 000007 grants
	// SELECT explicitly because `01-init.sql` ran before these tables
	// existed, and a missing grant surfaces as a permission error inside
	// retrieval at the first chat request.
	reader, err := pgx.Connect(ctx, readerDSN)
	if err != nil {
		t.Fatalf("connect as astro_ro: %v", err)
	}
	defer reader.Close(ctx)

	var readable int
	if err := reader.QueryRow(ctx,
		`SELECT count(*) FROM knowledge_chunks`).Scan(&readable); err != nil {
		t.Fatalf("astro_ro cannot read knowledge_chunks: %v", err)
	}
	if int64(readable) != counts.Chunks {
		t.Errorf("astro_ro sees %d chunks, writer wrote %d", readable, counts.Chunks)
	}

	// And still cannot write. The single-writer rule is enforced by
	// grants, and a test that only proves the read half would not notice
	// the day somebody grants INSERT to fix something.
	_, err = reader.Exec(ctx,
		`DELETE FROM knowledge_chunks WHERE chunk_index = 0`)
	if err == nil {
		t.Error("astro_ro deleted knowledge_chunks; the read-only grant is not holding")
	}
}

func TestAWrongWidthVectorIsRejectedByPostgres(t *testing.T) {
	// The reason the embedding crosses into Postgres as text and is cast
	// rather than being handed over as bytes: `::vector` validates the
	// width against the column. A width mismatch either fails here —
	// loud, fine — or lands in a column loose enough to accept it, after
	// which every similarity score in the product is meaningless and
	// nothing errors.
	ctx := context.Background()
	store, _, _, terminate := startStore(ctx, t)
	defer terminate()

	corpus := loadTestCorpus(t)[:1]

	for _, width := range []int{1, 767, 769} {
		t.Run(fmt.Sprintf("width-%d", width), func(t *testing.T) {
			_, err := knowledge.Ingest(ctx, corpus,
				&fixedEmbedder{model: "m", width: width}, store,
				knowledge.IngestOptions{BatchSize: 4, Force: true})
			if err == nil {
				t.Fatalf("a %d-dimension vector was accepted into vector(%d)",
					width, embeddingWidth)
			}
			if !strings.Contains(err.Error(), "dimension") &&
				!strings.Contains(err.Error(), "vector") {
				t.Errorf("error does not mention the vector: %v", err)
			}
		})
	}
}

func TestReIngestingIsIdempotentAgainstTheRealUniqueIndex(t *testing.T) {
	// §16: "Ingestion is deterministic and re-runnable without
	// duplicates". The fake store enforces identity with a Go map; this
	// asserts the real `ON CONFLICT` target matches the real
	// `kd_identity_idx`, which is the part that would fail as
	// "there is no unique or exclusion constraint matching the ON CONFLICT
	// specification" rather than as a duplicate.
	ctx := context.Background()
	store, _, _, terminate := startStore(ctx, t)
	defer terminate()

	corpus := loadTestCorpus(t)
	embedder := &fixedEmbedder{model: "m"}

	for run := 0; run < 3; run++ {
		opts := knowledge.IngestOptions{BatchSize: 4, Force: true}
		if _, err := knowledge.Ingest(ctx, corpus, embedder, store, opts); err != nil {
			t.Fatalf("run %d: %v", run, err)
		}
	}

	counts, err := store.Counts(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if int(counts.Documents) != len(corpus) {
		t.Errorf("three runs produced %d documents for %d files",
			counts.Documents, len(corpus))
	}

	// Chunks too. The document upsert could be idempotent while chunk
	// inserts accumulated, which is what `DeleteKnowledgeChunks` before
	// every insert exists to prevent.
	expected := 0
	for _, document := range corpus {
		expected += len(document.Chunks)
	}
	if int(counts.Chunks) != expected {
		t.Errorf("three runs produced %d chunks for %d chunked", counts.Chunks, expected)
	}
}

func TestShrinkingADocumentLeavesNoOrphanChunks(t *testing.T) {
	// Against the real UNIQUE (document_id, chunk_index). Orphan chunks
	// would still match keyword search and still be retrieved — the only
	// chunks in the corpus whose text no authored file contains.
	ctx := context.Background()
	store, pool, _, terminate := startStore(ctx, t)
	defer terminate()

	long := syntheticDocument("Shrinking", strings.Repeat("A sentence that is here. ", 40), "sum-1")
	short := syntheticDocument("Shrinking", "One short sentence now.", "sum-2")
	cfg := knowledge.ChunkConfig{SizeTokens: 60, OverlapTokens: 10}

	for _, doc := range []*knowledge.Document{long, short} {
		chunks, err := knowledge.ChunkDocument(doc, cfg)
		if err != nil {
			t.Fatal(err)
		}
		_, err = knowledge.Ingest(ctx,
			[]knowledge.ChunkedDocument{{Document: doc, Chunks: chunks}},
			&fixedEmbedder{model: "m"}, store, knowledge.IngestOptions{BatchSize: 4})
		if err != nil {
			t.Fatal(err)
		}
	}

	var stored int
	var content string
	err := pool.QueryRow(ctx, `
		SELECT count(*), min(content) FROM knowledge_chunks`).Scan(&stored, &content)
	if err != nil {
		t.Fatal(err)
	}

	if stored != 1 {
		t.Errorf("%d chunks remain after shrinking the document to one", stored)
	}
	if !strings.Contains(content, "One short sentence now.") {
		t.Errorf("the surviving chunk is the old one: %q", content)
	}
}

func TestARealTransactionRollsBackAPartialDocument(t *testing.T) {
	// §4 requires documents and chunks to go in together. The fake store
	// models this with a snapshot; this asserts the real Postgres
	// transaction does it, which is the claim that actually ships.
	ctx := context.Background()
	store, pool, _, terminate := startStore(ctx, t)
	defer terminate()

	doc := syntheticDocument("Will Fail",
		strings.Repeat("A sentence that is here. ", 40), "sum-1")
	chunks, err := knowledge.ChunkDocument(doc,
		knowledge.ChunkConfig{SizeTokens: 60, OverlapTokens: 10})
	if err != nil {
		t.Fatal(err)
	}
	if len(chunks) < 3 {
		t.Fatalf("need several chunks, got %d", len(chunks))
	}

	// A vector of the wrong width on the LAST chunk only, so the document
	// and the earlier chunks are already written when the failure lands.
	embedder := &fixedEmbedder{model: "m", wrongWidthAt: len(chunks) - 1}

	_, err = knowledge.Ingest(ctx,
		[]knowledge.ChunkedDocument{{Document: doc, Chunks: chunks}},
		embedder, store, knowledge.IngestOptions{BatchSize: 64})
	if err == nil {
		t.Fatal("the bad vector was accepted")
	}

	var documents, storedChunks int
	if err := pool.QueryRow(ctx, `
		SELECT (SELECT count(*) FROM knowledge_documents),
		       (SELECT count(*) FROM knowledge_chunks)`).Scan(&documents, &storedChunks); err != nil {
		t.Fatal(err)
	}

	if documents != 0 || storedChunks != 0 {
		t.Errorf("after rollback: %d documents, %d chunks — both must be 0, "+
			"because a document visible without its chunks is one retrieval "+
			"cannot reach but the corpus count includes", documents, storedChunks)
	}
}

func TestStoredMetadataIsQueryableByTheRetrievalFilter(t *testing.T) {
	// The chunk metadata is only useful if `metadata @> $1` matches it —
	// which is how §4's retrieval SQL narrows before it ranks, through the
	// `jsonb_path_ops` GIN index. A chunker that wrote the right JSON into
	// the wrong shape would pass every unit test in this repo.
	ctx := context.Background()
	store, pool, _, terminate := startStore(ctx, t)
	defer terminate()

	corpus := loadTestCorpus(t)
	if _, err := knowledge.Ingest(ctx, corpus, &fixedEmbedder{model: "m"}, store,
		knowledge.IngestOptions{BatchSize: 4}); err != nil {
		t.Fatal(err)
	}

	// Taken from the corpus rather than hardcoded, so this test keeps
	// meaning if the fixture changes.
	wanted := jsonOfRaw(t, corpus[0].Chunks[0].Metadata)
	if len(wanted) == 0 {
		t.Skip("the first fixture chunk carries no metadata")
	}

	for key, value := range wanted {
		if _, isList := value.([]any); isList {
			// Containment against an array is a different predicate; the
			// retriever uses scalar keys.
			continue
		}

		filter, err := json.Marshal(map[string]any{key: value})
		if err != nil {
			t.Fatal(err)
		}

		var matches int
		if err := pool.QueryRow(ctx,
			`SELECT count(*) FROM knowledge_chunks WHERE metadata @> $1`,
			string(filter)).Scan(&matches); err != nil {
			t.Fatalf("containment query on %s: %v", filter, err)
		}
		if matches == 0 {
			t.Errorf("no chunk matches %s, but a chunk was stored with it", filter)
		}
	}
}

// ─── fixtures and plumbing ───────────────────────────────────────────

// fixedEmbedder returns a constant, correctly-shaped vector.
//
// Constant rather than content-derived: this file is about the database,
// and `ingest_test.go` already asserts that each chunk gets the vector for
// its own text. A known first component (0.5) makes the round-trip
// assertion above exact.
type fixedEmbedder struct {
	model string

	// width overrides the vector width, for the rejection test.
	width int

	// wrongWidthAt makes exactly one vector the wrong width, counted
	// across the whole run, so a failure lands mid-document.
	wrongWidthAt int

	seen int
}

func (e *fixedEmbedder) Embed(_ context.Context, texts []string) ([][]float32, string, error) {
	width := e.width
	if width == 0 {
		width = embeddingWidth
	}

	vectors := make([][]float32, len(texts))
	for index := range texts {
		this := width
		if e.wrongWidthAt > 0 && e.seen+index == e.wrongWidthAt {
			this = width - 1
		}
		vector := make([]float32, this)
		if this > 0 {
			vector[0] = 0.5
		}
		for component := 1; component < this; component++ {
			vector[component] = float32(component) / float32(this)
		}
		vectors[index] = vector
	}

	e.seen += len(texts)
	return vectors, e.model, nil
}

func loadTestCorpus(t *testing.T) []knowledge.ChunkedDocument {
	t.Helper()

	corpus, err := loadCorpus(
		filepath.Join("..", "..", "internal", "knowledge", "testdata", "corpus"),
		knowledge.DefaultChunkConfig())
	if err != nil {
		t.Fatalf("load fixtures: %v", err)
	}

	documents := make([]knowledge.ChunkedDocument, 0, len(corpus))
	for _, loaded := range corpus {
		documents = append(documents, knowledge.ChunkedDocument{
			Document: loaded.doc, Chunks: loaded.chunks,
		})
	}
	return documents
}

func syntheticDocument(title, body, checksum string) *knowledge.Document {
	return &knowledge.Document{
		Title:           title,
		Category:        "test",
		Source:          "editorial",
		Language:        "en",
		AstrologySystem: "vedic",
		Authority:       50,
		Version:         1,
		Body:            body,
		Metadata:        json.RawMessage(`{"topic":["testing"]}`),
		Checksum:        checksum,
		Path:            title + ".md",
	}
}

func jsonOfRaw(t *testing.T, raw json.RawMessage) map[string]any {
	t.Helper()
	var fields map[string]any
	if err := json.Unmarshal(raw, &fields); err != nil {
		t.Fatalf("metadata is not an object: %v", err)
	}
	return fields
}

// startStore brings up pgvector Postgres with every migration applied.
func startStore(ctx context.Context, t *testing.T) (
	store *pgStore, pool *pgxpool.Pool, readerDSN string, terminate func(),
) {
	t.Helper()

	initSQL, err := filepath.Abs(filepath.Join(
		"..", "..", "..", "..", "infrastructure", "docker", "init", "01-init.sql"))
	if err != nil {
		t.Fatalf("resolve init script: %v", err)
	}
	if _, err := os.Stat(initSQL); err != nil {
		t.Fatalf("bootstrap SQL not found at %s: %v", initSQL, err)
	}

	container, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: testcontainers.ContainerRequest{
			// pgvector's image, not plain postgres: `vector(768)` needs the
			// extension and `01-init.sql` creates it.
			Image:        "pgvector/pgvector:pg16",
			ExposedPorts: []string{"5432/tcp"},
			Env: map[string]string{
				"POSTGRES_USER":     "astro",
				"POSTGRES_PASSWORD": "astro",
				"POSTGRES_DB":       "astro_dev",
			},
			Files: []testcontainers.ContainerFile{{
				HostFilePath:      initSQL,
				ContainerFilePath: "/docker-entrypoint-initdb.d/01-init.sql",
				FileMode:          0o644,
			}},
			WaitingFor: wait.ForLog("database system is ready to accept connections").
				WithOccurrence(2).
				WithStartupTimeout(90 * time.Second),
		},
		Started: true,
	})
	if err != nil {
		testsupport.ContainerUnavailable(t, "Postgres", err)
	}

	host, err := container.Host(ctx)
	if err != nil {
		t.Fatalf("container host: %v", err)
	}
	port, err := container.MappedPort(ctx, "5432/tcp")
	if err != nil {
		t.Fatalf("mapped port: %v", err)
	}

	dsn := func(user, pass string) string {
		return fmt.Sprintf("postgresql://%s:%s@%s:%s/astro_dev?sslmode=disable",
			user, pass, host, port.Port())
	}

	pool, err = pgxpool.New(ctx, dsn("astro", "astro"))
	if err != nil {
		t.Fatalf("pool: %v", err)
	}

	applyEveryMigration(ctx, t, pool)

	return newPGStore(pool), pool, dsn("astro_ro", "astro_ro"), func() {
		pool.Close()
		_ = container.Terminate(context.Background())
	}
}

// applyEveryMigration runs each *.up.sql in order, as the real deployment
// does. Reading the files rather than duplicating the schema means this
// test fails if a future migration forgets its grants.
func applyEveryMigration(ctx context.Context, t *testing.T, pool *pgxpool.Pool) {
	t.Helper()

	dir, err := filepath.Abs(filepath.Join("..", "..", "db", "migrations"))
	if err != nil {
		t.Fatalf("resolve migrations: %v", err)
	}

	files, err := filepath.Glob(filepath.Join(dir, "*.up.sql"))
	if err != nil {
		t.Fatalf("glob migrations: %v", err)
	}
	if len(files) == 0 {
		t.Fatalf("no migrations in %s", dir)
	}
	sort.Strings(files) // numeric prefixes make lexical order correct

	for _, file := range files {
		content, err := os.ReadFile(file)
		if err != nil {
			t.Fatalf("read %s: %v", file, err)
		}
		if _, err := pool.Exec(ctx, string(content)); err != nil {
			t.Fatalf("apply %s: %v", filepath.Base(file), err)
		}
	}
}
